### ISSUE TITLE
Assertion triggered by file converted from `.osm` to `.pbf` using `libosmium`

### ISSUE THREAD

**Issue by danpat** [osmcode/libosmium#102]
We've got a `.osm` file converted to `.pbf` using `libosmium`.  We're using it with OSRM.

While reading the file with `osrm-extract`, we're hitting the following assertion:

    osrm-extract: osrm-backend/third_party/libosmium/include/osmium/io/detail/pbf_parser.hpp:295: void osmium::io::detail::PBFPrimitiveBlockParser::parse_dense_node_group(const OSMPBF::PrimitiveGroup&): Assertion `v > 0' failed.

This assertion so far has only appeared when building on Ubuntu 15.04 using the packaged `libosmium`:

    $ dpkg -l | grep osm
    ii  libosmpbf-dev                          1.3.3-2build1                amd64        C headers for OpenStreetMap PBF   file format

This does not seem to trigger when running the same `osrm-extract` command on OSX using osmpbf binaries we've built internally.

On both platforms, we can `osrm-extract` just fine using the original `.osm` XML file.

Unfortunately, I can't share the `.pbf` file, it's generated from some private road network data.

**Comment by daniel-j-h** [comment]
To be more precise: the tool used for converting between the `.osm` and the `.pbf` file was the `osmium_convert` example from the libosmium 2.2.0 release.

**Comment by danpat** [comment]
Also, I stand corrected, `osrm-extract` has an internal import of `libosmium`, it's not using the versions linked above.

See: https://github.com/Project-OSRM/osrm-backend/tree/master/third_party/libosmium

**Comment by joto** [comment]
Where is the original file (the `.osm` file) from? It looks like it is missing version information. Why are you converting the .osm file to .pbf first before reading into osrm?

**Comment by danpat** [comment]
The original `.osm` file is being generated from some proprietary internal map data.

`.pbf` loading seems significantly faster for the planet-sized OSM data, and is a lot faster to move around because of the smaller size.  We're just preparing for global-scale iterations, the `.osm` file works great for what we're doing initially, we just notice a problem with parsing the converted `.pbf` that seemed worth mentioning.

**Comment by joto** [comment]
This has something to do with attributes like "version" not being set. There is some inconsistency in how libosmium handles those cases. I have to think about how to best solve these.

**Comment by danpat** [comment]
Workaround for us is to use use the XML files for now, but it would be nice for `libosmium` to barf on XML rather than silently creating a PBF that it won't parse later.

**Comment by joto** [comment]
The new pbf code doesn't care any more if the version is not set. So this should work now.
