### ISSUE TITLE
Input/output using external programs

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#11]
Currently input and output of osm.gz and osm.bz2 use the external programs gzip and bzip2. When we didn't have multithreading this wasn't such a bad idea, because at least the compressing and umcompressing was done in a separate process speeding things up. But it makes everything a little more brittle (what happens if it can't find that executable?) and, more importantly, it doesn't work on Windows, where we can't just fork the process.

Now that we have multithreading in Osmium, compressing and uncompressing should be done in extra threads using the respective libraries.

A similiar issue is the use of the "curl" executable for downloading OSM files from a URL. This should also be done in a thread using the curl or some other http library.

**Comment by joto** [comment]
I am thinking about using http://cpp-netlib.org/ for integrating the read-via-HTTP part. Looks like it is easier to use then libcurl which has a horrible API. Any opinions?

**Comment by mloskot** [comment]
> easier to use then libcurl which has a horrible API. Any opinions?

Since GDAL is already a dependency, a viable alternative might be to use its libcurl wrapper: [CPLHTTPFetch](https://github.com/OSGeo/gdal/blob/trunk/gdal/port/cpl_http.cpp).

**Comment by joto** [comment]
@mloskot GDAL is only a dependency for very few things that osmium does. Dragging this into something basic like I/O is not an option.

**Comment by mloskot** [comment]
@joto Right, since it's not a hard dep. Although API/quality-wise cpp-netlib is a very good piece, there are lighter-simpler alternatives. So, whatever is your policy regarding deps and deps of deps, etc.

**Comment by joto** [comment]
It doesn't look like this will be happening anytime soon. Closing here.
