### ISSUE TITLE
Problem with "delta encode iterator" test

### ISSUE THREAD

**Issue by alex85k** [osmcode/libosmium#120]
When building and testing on Windows (debug version), addtitonal checking revealed iterator-related problem.

The test fails with debug assertion when accessing  end() via `l` in DeltaEncodeIterator constructor
```C++
 std::vector<int> data = { 4, 5, 13, 22, 12 };

    auto l = [](std::vector<int>::const_iterator it) -> int {
        return *it;
    };

    typedef osmium::util::DeltaEncodeIterator<std::vector<int>::const_iterator, decltype(l), int> it_type;
    it_type it(data.begin(), data.end(), l);
    it_type end(data.end(), data.end(), l); <--- HERE IT TRIES TO ACCESS *(data.end())
```
https://github.com/osmcode/libosmium/blob/master/test/t/util/test_delta.cpp#L56
https://github.com/osmcode/libosmium/blob/master/include/osmium/util/delta.hpp#L112
I hope you'll find the best way to fix this.

**Comment by joto** [comment]
Hm. Why doesn't this show up in the appveyor tests?

**Comment by alex85k** [comment]
Maybe the Appveor still uses the release runtime? Dependencies packs seems to be the same...
