### ISSUE TITLE
Provide forward declarations of commonly used types.

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#123]
It's quite common that the use-case comes up to write a function that takes an osmium type by const-ref, e.g. in a header (simplified a bit): 

    class RestrictionParser {
        bool TryParse(const osmium::Relation&);
    };

for which I have to forward-declare `Relation` manually, otherwise I would have to include the full-blown osmium header into the `RestrictionParser` header, increasing compile times and coupling quite a bit!

Instead of the user doing `namespace osmium { class Relation; }` for all the osmium types, it would be great to provide forward-declarations with osmium. This mimics how Boost provide e.g. the header `optional_fwd.hpp` or how the stdlib provides the header `iosfwd`.

**Comment by joto** [comment]
Good idea. Can we have one one header only for this or would be need multiple for different sets of classes? What happens if we forward-declare a class, never use it, and then never declare it anywhere else? Does the compiler simply ignore it? I don't want to force users to say, get the declaration for `class Area` when he is not doing anything with areas only because it is in the same file as `class Node`.

**Comment by daniel-j-h** [comment]
What you get with the single header `<iosfwd>` are multiple declarations such as `std::ifstream`, `std::ofstream` and so on. If the user has to include a header such as `<osmium/osm/area_fwd.hpp>` for every forward-declaration, I see no convenience in this.

If you forward-declare a function / class and never use it, nothing happens. If you forward-declare it and use it without providing a proper definition later on, the compiler complains about an incomplete type (I think in the worst case the linker should complain, as it is unable to find a definition).

Take a look, only forward-declaration:
http://coliru.stacked-crooked.com/a/061dac0c7e051bcb

Proper include:
http://coliru.stacked-crooked.com/a/e226b69a78078966

I think what could be a problem is that osmium has many template functions and template classes, where forward-declaring brings us no real benefit --- or better, we don't know the types for the template yet to forward-declare the resulting types. It could make sense to provide a public header with something like:

    using NodeFilter = Filter<Node>;  // simplified

to make the user's life easier for common types, but that's a different goal of what this ticket tries to achieve.
