### ISSUE TITLE
Improve Travis CI setup mainly wrt. modern compiler coverage

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#124]
This is a master ticket for tracking and discussing improving the Travis CI integration.

- ~~[ ] fail fast, `set -e` on current scripts~~
- [x] integrate different compilers, release, debug builds

I'm currently playing with improving the OSRM Travis CI integration (as we are not even using the new container infrastructure right now). I'm hoping to re-use some of this integration work here.

Playground is here: https://travis-ci.org/daniel-j-h/cpp-travis-setup
and: https://github.com/daniel-j-h/cpp-travis-setup/blob/master/.travis.yml

**Comment by daniel-j-h** [comment]
First results are here:
https://travis-ci.org/daniel-j-h/libosmium

This is running from my fork at:
https://github.com/daniel-j-h/libosmium

in which I basically just modified the `.travis.yml` config.

**Comment by daniel-j-h** [comment]
Next goals:

- [ ] [ASan / TSan / MSan / UBSan](https://github.com/Project-OSRM/osrm-backend/issues/1601) builds

**Comment by daniel-j-h** [comment]
Unfortunately the Sanitizers from the deb packages are broken right now, bug here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779785

**Comment by daniel-j-h** [comment]
@joto would love to get your thoughts on this: if you want me to change something, if this is a good start, or what you need before considering merging it.

**Comment by joto** [comment]
@daniel-j-h: interesting work. Shame we have the problems on travis with the sanitizers, but I guess this will be fixed some day. Lets keep this open and revisit once the debian packages are fixed on travis.

**Comment by daniel-j-h** [comment]
This landed in https://github.com/osmcode/libosmium/commit/4ad6e4340e8ef8cf0f50e1783e6d6c16d5cfa737 closing here.
