### ISSUE TITLE
Consider making `SegmentList` part of the public interface

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#127]
For cutting a `Way` into its `Segment`s, I found (by accident) the private `SegmentList` from the area builder. With its helper functions for extracting `Segment`s from `Way`s and making them unique, it makes the perfect class for our use case.

Is there a reason for having `Segment` publicly available, but `SegmentList` hidden, when it is so closely related and provides commonly used functionality?

Note: I will probably use it anyway via `osmium::area::detail` :P but it would be great to have it officially available through the public interface.

**Comment by joto** [comment]
Until now nobody ever asked for `SegmentList` and I have never used it anywhere but in the Area code. Usually if I don't see a general use for something I don't make it part of the public interface that I have to support for a long time. `SegmentList` has some code very much tied to the Area stuff, so the way it looks now, I wouldn't want it to be a general class. If you can find a way to extract the general code from the Area-specific code, this might be a way forward.

**Comment by daniel-j-h** [comment]
Sounds reasonable. I wanted to use it for splitting ways, in order to do the routing on segments.
Looking more into it, I can see the segments logic doing sorting based on coordinates, which makes sense for areas but not so much for my splitting work. Hmm closing here.
