### ISSUE TITLE
only include/osmium is installed

### ISSUE THREAD

**Issue by dforsi** [osmcode/libosmium#133]
From the readme I had the impression that protozero and utf8 would be installed by make install:

> The [protozero](https://github.com/mapbox/protozero) and [utf8-cpp](http://utfcpp.sourceforge.net/) header-only libraries are included in the libosmium repository.

The include directory of libosmium contains:
gdalcpp.hpp  osmium/  protozero/  utf8/  utf8.h
CMakeLists.txt has:
`install(DIRECTORY include/osmium DESTINATION include)`

**Comment by bdiscoe** [comment]
joto, I tried to enable this option today and it did not work.  However, I was able to fix it.

CMakeFiles.txt has:

if(INSTALL_UTFCPP)
    install(include/utf8.hpp DESTINATION include)
    install(DIRECTORY include/utf8 DESTINATION include)
endif()

but that is not the name of the header.  I fixed it like this:

if(INSTALL_UTFCPP)
    install(FILES include/utf8.h DESTINATION include)
    install(DIRECTORY include/utf8 DESTINATION include)
endif()

I don't know how to submit this as a change, so you may want to paste it in from here.  The INSTALL_GDALCPP also looks like it needs to be fixed, but I did not try it.

**Comment by joto** [comment]
@bdiscoe thanks. I have added your fix.
