### ISSUE TITLE
WKB factory should allow for configurable srid

### ISSUE THREAD

**Issue by lonvia** [osmcode/libosmium#138]
When writing EWKB the srid is hard-coded to 4326, which makes it impossible to use the factory for writing geometries in other projections. Please note that the geometry to be written has already been reprojected in my case. Therefore, even if the epsg() from the projection template parameter was taken into account, it is only of limited use unless another special IdentityProjection class is defined.

**Comment by joto** [comment]
SRIDs are now set automatically. Setting them manually is not supported, because Osmium knows about the right SRID, because it always handles coordinates internally in 4326. The (E)WKB writer is only intended to be used on non-projected coordinates, other uses are outside the scope of Osmium.
