### ISSUE TITLE
noob issue: location=(undefined,undefined)

### ISSUE THREAD

**Issue by titusnicolae** [osmcode/libosmium#142]
I just got started with osmium. I'm trying to iterate over the nodes in ways. For some reason their lat long is undefined as shown bellow.
This the code i tried:

    #include <iostream>
    #include <osmium/io/any_input.hpp>
    #include <osmium/handler.hpp>
    #include <osmium/visitor.hpp>

    struct CountHandler : public osmium::handler::Handler {
        void way(osmium::Way& way) {
            for (const osmium::NodeRef& nr : way.nodes()) {
                std::cout << "ref=" << nr.ref() << " location=" << nr.location() << "\n";
            }
        }
    };

    int main() {
        std::string input_filename = "egypt-latest.osm.pbf";
        osmium::io::Reader reader(input_filename);
        CountHandler handler;
        osmium::apply(reader, handler);
        reader.close();
    }

Output:

    ref=2375831108 location=(undefined,undefined)
    ref=2375831102 location=(undefined,undefined)
    ref=2375831115 location=(undefined,undefined)
    ref=2375831152 location=(undefined,undefined)
    ref=2375831141 location=(undefined,undefined)
    ref=2375831104 location=(undefined,undefined)
    ref=2375831142 location=(undefined,undefined)
    ref=2375831085 location=(undefined,undefined)
    ref=105672308 location=(undefined,undefined)
    ref=2375831139 location=(undefined,undefined)
    ref=2375831114 location=(undefined,undefined)
    ref=105672309 location=(undefined,undefined)
    ref=2375831069 location=(undefined,undefined)

I've just downloaded the input file so that shouldn't be the issue.  
I tried to use `nr.location().lat()`, but it gives `osmium::invalid_location`
the makefile I used:

    all:
        clang++ -o test -std=c++11 -I ~/libosmium/include test.cpp -lpthread -lexpat -lz -lbz2

Thanks!

**Comment by daniel-j-h** [comment]
That's because ways only contain references to nodes, but you have to cache these nodes in order to be able to dereference the references. There is a `NodeLocationForWays` cache handler already in libosmium:

```c++
#include <osmium/osm/types.hpp>
#include <osmium/index/map/sparse_mem_array.hpp>
#include <osmium/handler/node_locations_for_ways.hpp>

using index_t = osmium::index::map::SparseMemArray<osmium::unsigned_object_id_type, osmium::Location>;
using cache_t = osmium::handler::NodeLocationsForWays<index_t>;

int main() {
  index_t index_positive;
  cache_t cache{index};
  // ...
  osmium::apply(reader, cache, your_handler);
}
```
The sparse index is great for smallish or medium extracts, the dense index is only needed for planet-sized extracts and helps keeping the memory overhead low.

Sidenote: I would add a few warning options to your compiler invocation, such as:

    -Wall -Wextra -pedantic

**Comment by titusnicolae** [comment]
I've seen that pattern with caching before but didn't get it. 
Now it makes sense, many thanks Daniel!

**Comment by HerrKlemmy** [comment]
Hi I have a question related to this topic and hope, that its ok, to open this issue again:

I got this NodeLocationsForWays - handler and also apply it to the Way-Handler and the example code works until the "last" Node. Even as the last one is printed, another try to read the location is done, and doesnt work (of course not) - but I dont know, why it tries to.

Here my code:

main:
```
auto otypes = osmium::osm_entity_bits::node | osmium::osm_entity_bits::way;
osmium::io::Reader reader{"file.osm", otypes};
osmium::apply(reader, entmh); */
namespace map = osmium::index::map;
using index_type = map::SparseMemArray<osmium::unsigned_object_id_type, osmium::Location>;
using location_handler_type = osmium::handler::NodeLocationsForWays<index_type>;
index_type index;
location_handler_type location_handler{index};

WayNodeHandler handler;
osmium::apply(reader, location_handler, handler);
```

Handler_
```
class WayNodeHandler : public osmium::handler::Handler {
public:
    void way(const osmium::Way& way) {
        for (const NodeRef& n : way.nodes()) {  
                try {
                    cout << "PULLERPUNKT:" << n.ref() << ": " << n.location().lon() << ", " << n.location().lat() << '\n';
                } catch (const exception& e) { 
                    cout << "Nope: " << e.what() << endl;
                }
        }
    }
};
```

and the output:

```
[...]
PULLERPUNKT:881517933: 8.28077, 50.0291
PULLERPUNKT:4081572995: 8.28144, 50.0289
PULLERPUNKT:2791228027: 8.28149, 50.0289
libc++abi.dylib: terminating with uncaught exception of type osmium::invalid_location: invalid location
Abort trap: 6
```

The "PULLERPUNKT:2791228027" is the last one in the last way in the file, so i dont know, why this comes.

Somebody got an idea?

**Comment by joto** [comment]
Next time please open a new issue. This is not a discussion forum, but we track each issue separately in, well, a new issue.

Your error might be thrown from the location_handler. Use `location_handler.ignore_errors();` to suppress that error. And check that your `catch` clause actually catches the right thing, I don't know what `exception` is in your program as you didn't post the whole thing. Maybe you want to catch `osmium::invalid_location` instead.
