### ISSUE TITLE
Adding custom tags to an osmium::Way

### ISSUE THREAD

**Issue by jcoupey** [osmcode/libosmium#145]
I hope this is ok to post here as this is rather a question.

I would like to add custom tags to some ways based on their position (e.g. their first node being in a given bounding box).

Searching the osm-dev archives, I found a pointer to a syntax like `way.tags().add(...)` but this seem to be irrelevant for the current code.
I've been browsing the code base and got the idea that an `OSMObjectBuilder` might be of use but I fail to see how I could use it to deal with a way in my own handler.

What I am using so far is:
```
struct InBoxHandler : public osmium::handler::Handler {
  osmium::Box box;
  osmium::io::Writer writer;

  void way(osmium::Way& way) {
    if(box.contains(way.nodes()[0].location())){
      // How to add custom tag to way here??
    }
    writer(std::move(way));
  }

  InBoxHandler(const std::string &filename, osmium::io::Header& header):
    writer(filename, header, osmium::io::overwrite::allow) {}
};
```

Any hint appreciated!

**Comment by joto** [comment]
Unfortunately this is rather complex to do. You can not just change OSM objects in libosmium. You have to first create a buffer and then basically copy the existing object into it while changing whatever you want changed, in this case adding the extra tag. There is some code in `test/t/builder/test_attr.cpp` that can give you an idea on how to do this.

I don't know why you wan to add this tag, but maybe there is a better way to keep this information somewhere outside the OSM object. If you tell us what you want to accomplish in the end, maybe we can find a better way how to do this.

**Comment by jcoupey** [comment]
Thanks, I'll try to come up with something using the approach you suggested and let you know how it goes.

I wish to add additional information to ways in order to weight on how they will be treated by OSRM during extraction. Having this embedded in the OSM object makes it really easy afterwards (just a matter of adding a few lines to parse the extra tag in the lua profile used by OSRM).

**Comment by jcoupey** [comment]
I'm using:
```
osmium::memory::Buffer wbuffer(1024*10, osmium::memory::Buffer::auto_grow::yes);
osmium::builder::add_way(wbuffer,
                         osmium::builder::attr::_id(way.id()),
                         osmium::builder::attr::_nodes(way.nodes()),
                         osmium::builder::attr::_tags(way.tags()),
                         osmium::builder::attr::_tag("my_key", "my_value"));
```
then moving the new `wbuffer` to be written instead of the initial `way`, which seems to do exactly what I need.

Thanks for pointing me in the right direction!

**Comment by pcumino** [comment]
Hi!
@jcoupey, I wonder if you could show more details about your implementation. I believe my issue is very close to yours.

The tags shall be added to ways based on the location (latitude and longitude). The information comes from a JSON file which I can easily modify if neccessary. I need to insert may be set as in this list below:
```
[lat], [lon], [tag_value]
[lat], [lon], [tag_value]
...
[lat], [lon], [tag_value]
```
`test/t/builder/test_attr.cpp` is not clear how it works.
Is there any example file that shows details about how the osmium writes on _.pbf_ ?

Do you have any suggestion?

Thanks

**Comment by joto** [comment]
@pcumino Please do not revive closed issues. If you have a question about libosmium use, open a new issues with your specific question. Anything else does not belong here.
