### ISSUE TITLE
Strange tag interpretation when building areas

### ISSUE THREAD

**Issue by imagico** [osmcode/libosmium#155]
Looks like the current way areas are built results in some strange interpretations of tags.  For example here:

http://www.openstreetmap.org/relation/1152508

with a multipolygon with a name tag and a closed way outer ring with a `natural=water` tag.  This gets processed into a single area representing the multipolygon with the name tag and no area feature with `natural=water`.

IMO there are only two possible consistent interpretations of this data:
- assume area tags on outer ways apply to the multipolygons at least in non-ambiguous cases like here and transfer them accordingly.
- assume way tags always apply to the way itself and generate a second area representing the closed way with its tags.

It would be good if osmium could be instructed to adhere to at least one of these interpretations (and ideally report the details with `debug_level=2`).

**Comment by joto** [comment]
The relation is tagged wrong. You either have to have all tags on the relation (preferred), or all tags on the outer way(s) ("old style" tagging). But a mixture is not supported. This would mean Osmium has to understand what the tags mean and whether it can merge them or not.

Long-term this problem will only be solved when we abolish the old style of tagging and only support

**Comment by imagico** [comment]
Please keep in mind the example shown is just an example - the fact that tagging there is wrong does not invalidate this issue.

A better example would be an island (closed way with `place=island`) that is almost fully forested (multipolygon with `natural=wood`) except for a lake in the middle (closed ways with `natural=water`) - according to Osmium you cannot reuse the way with `place=island` as part of the wood multipolygon because it then ignores this as a separate area.

Note this is not in any way a rare occurrence and has nothing to do with old style vs. new style tagging of multipolygons.  Like here:

http://www.openstreetmap.org/relation/3961637
http://www.openstreetmap.org/relation/3002662

I don't think tag interpretation is required for osmium to do better - you just would have to make sure to create separate areas for closed ways that are outer rings in multipolygons unless their tags are all transferred to the multipolygon using the logic currently in place - or in other words: only drop closed ways as areas if all their tags have been transferred to a multipolygon.

**Comment by imagico** [comment]
Fix for this is now on https://github.com/imagico/libosmium/tree/mp-outer-rings - IMO this is an improvement as is because it recognizes a lot of correctly tagged cases (like the ones in my second comment) which are lost right now.  The possible addition indicated in the source comment might help to get more reasonable results in cases with ambiguous tagging though.  And of course it would be good to allow turning it on/off with configuration options.

**Comment by joto** [comment]
Now that there are no old-style multipolygons any more, this should be correctly handled by the [new multipolygon assembler code](https://github.com/osmcode/libosmium/blob/master/include/osmium/area/assembler.hpp). The [old assembler](https://github.com/osmcode/libosmium/blob/master/include/osmium/area/assembler_legacy.hpp) still supporting old-style multipolygons will not be changed.
