### ISSUE TITLE
Scientific notation for lat/lon in XML

### ISSUE THREAD

**Issue by lonvia** [osmcode/libosmium#158]
Libosmium can no longer parse scientific notation for floats in lat/lon but there is a very prominent producer of this: the OSM API. Example: http://www.openstreetmap.org/api/0.6/node/3286696168/1

    <osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
      <node id="3286696168" changeset="28121089" timestamp="2015-01-13T21:04:17Z" version="1" visible="true" user="c2r" uid="5926" lat="51.8163125" lon="3.2e-05"/>
    </osm>

See also https://github.com/openstreetmap/openstreetmap-website/issues/341 and https://github.com/openstreetmap/osm2pgsql/pull/592

**Comment by joto** [comment]
Fixed in 45624292887ecfc0b0df574075c2b7f122c37e4f.
