### ISSUE TITLE
Fix DenseFileArray support for Windows

### ISSUE THREAD

**Issue by brano543** [osmcode/libosmium#159]
I have tried to used the create_node_cache example,however there is problem with off_t on Windows,it is set to uint32_t even on 64 bit build. If i exchange off_t with uint64_t, it doesn´t work either, even for 340 KB PBF it never finishes and if i stop it after few seconds it creates like 4 GB index file.

**Comment by joto** [comment]
@brano543 The size of the "DenseFileArray" file *depends on the largest ID* in the OSM input file, so it can be huge even for small inputs, for most OSM files it will be more that 32GB these days. For small PBFs you should probably use "SparseFileArray", its size *depends on the number of IDs* in the input file.

@BergWerkGIS Any ideas about the Windows issue here?

**Comment by BergWerkGIS** [comment]
@brano543 trying to replicate your problem as closely as possible.

Could you
* verify your are using [osmium_create_node_cache.cpp](https://github.com/osmcode/libosmium/blob/master/examples/osmium_create_node_cache.cpp)
* share which PBF you are using
* share your environment, e.g. Windows 10, VS2015 Update 3, ...
* share how you built `osmium_create_node_cache`, e.g. from where you got the dependencies, ...

**Comment by BergWerkGIS** [comment]
Looks like I can reproduce the crash:

* downloaded and extracted dependencies https://mapbox.s3.amazonaws.com/windows-builds/windows-build-deps/libosmium-deps-win-14.0-x64.7z
* added env vars and paths on the console like in [appveyor.yml](https://github.com/osmcode/libosmium/blob/115ae235ce203b49d5b2f41d18a2d247b1863d32/appveyor.yml)
* started VS from the console
* created a new VS Win32 console project
* added 
  * `osmium_create_node_cache.cpp`
  * `libbz2.lib;zlibwapi.lib;libexpat.lib;Ws2_32.lib` and their respective directories as `Additional Dependencies` and `Additional Library Directories`.

Built was successful, but running 
```
create_node_cache.exe monaco-latest.osm.pbf monaco.cache
``` 
crashed after a few seconds leaving a 2GB `monaco.cache`.

Investigating ...

**Comment by BergWerkGIS** [comment]
Exception seem to be thrown in [`include/osmium/util/memory_mapping.hpp::resize_fd`](https://github.com/osmcode/libosmium/blob/115ae235ce203b49d5b2f41d18a2d247b1863d32/include/osmium/util/memory_mapping.hpp#L159)

![image](https://cloud.githubusercontent.com/assets/4549888/17435290/5cb86994-5aff-11e6-81b0-fb1d6d45e00d.png)

**Comment by BergWerkGIS** [comment]
Ah, actual error happens in [include/osmium/util/file.hpp::resize_file](https://github.com/osmcode/libosmium/blob/115ae235ce203b49d5b2f41d18a2d247b1863d32/include/osmium/util/file.hpp#L96-L100).
Didn't see it in the debugger before because it's inline.
Now I also know, what @brano543 meant with `off_t`.

![image](https://cloud.githubusercontent.com/assets/4549888/17435670/f0deb6a8-5b01-11e6-92ed-37d5fed2ff79.png)

**Comment by BergWerkGIS** [comment]
Casting `size_t` to `off_t` fails: `2151474832` -> `-2143492464`:

![image](https://cloud.githubusercontent.com/assets/4549888/17436647/159ffe74-5b08-11e6-9508-4e4c0af63d81.png)

**Comment by BergWerkGIS** [comment]
@joto maybe cast fails because 
* `size_t` == `unsigned __int64`
* `off_t` == `long`

??


![image](https://cloud.githubusercontent.com/assets/4549888/17436708/7c22bdd0-5b08-11e6-80d0-1bce82cfa06d.png)

![image](https://cloud.githubusercontent.com/assets/4549888/17436720/962e3448-5b08-11e6-8bbc-86d65c9efe1d.png)

**Comment by brano543** [comment]
I was able to fix this with 
```
#if defined __LP64__ || defined(_WIN64)
typedef int64_t OffsetType;
#else
typedef uint32_t OffsetType;
#endif
```
and changing off_t to OffsetType in memory_mapping.hpp and util/file.hpp. But even with this fix i did yesterday it never finished creating the file even for 340 kB Pbf file.

**Comment by brano543** [comment]
I also wanted to create the index while parsing the file in parallel. I still have a problem with understanding some internals of libosmium, because the reading is done multithreaded,but i would also like to parse OSM entities in parallel. I got inspired by OSRM,but still there is a problem i don´t know how to make private copy of the class HighWayTagChecker for each thread. Can you also hep me with that? My code
```
//parser
#include <osmium/io/pbf_input.hpp>
//filtering functions
#include <highway/HighwayTagChecker.h>
#include <poi/PoiTagChecker.h>
//intel threading building blocks
#include <tbb/parallel_for.h>
#include <tbb/tbb.h>
//additional includes
#include <stdio.h>
#include <chrono>

class HighwayTagChecker
{
	SpeedTable speedtable;
public:	
	HighwayTagChecker()
	{
		speedtable = SpeedTable();
	}
	HighwayTagChecker (HighwayTagChecker &other)
	{
		speedtable = other.speedtable;
	}
	HighWay* getHighway(const osmium::Way &way);
};


int main(int argc, char* argv[]) {

	if (argc != 2) {
		std::cerr << "Usage: " << argv[0] << " OSMFILE\n";
		exit(1);
	}

	std::string fileName(argv[1]);

	osmium::io::File infile(fileName);
	osmium::io::Reader reader(infile);

	//initialize parser class
	Serializer serializer = DiskSerializer();
	HighwayTagChecker ht = HighwayTagChecker();
	PoiTagChecker pt = PoiTagChecker();


	std::atomic<std::uint64_t> NodeCount = 0;
	std::atomic<std::uint64_t> WayCount = 0;
	std::atomic<std::uint64_t> RelationCount = 0;

	std::atomic<std::uint64_t> NodePoiCount = 0;
	std::atomic<std::uint64_t> WayPoiCount = 0;

	std::atomic<std::uint64_t>HighwayCount = 0;

	high_resolution_clock::time_point t1 = high_resolution_clock::now();

	// initialize vectors holding parsed objects
	tbb::concurrent_vector<osmium::memory::Buffer::const_iterator> nodes;
	tbb::concurrent_vector<osmium::memory::Buffer::const_iterator> ways;

	while (const osmium::memory::Buffer buffer = reader.read())
	{
		// create a vector of iterators into the buffer
		std::vector<osmium::memory::Buffer::const_iterator> osm_elements;
		for (auto iter = std::begin(buffer), end = std::end(buffer); iter != end; ++iter)
		{
			osm_elements.push_back(iter);
		}

		// clear resulting vectors
		nodes.clear();
		ways.clear();


		// parse OSM entities in parallel, store in resulting vectors
		tbb::parallel_for(
			tbb::blocked_range<std::size_t>(0, osm_elements.size()),
			[&](const tbb::blocked_range<std::size_t> &range) 
		{
			for (auto x = range.begin(), end = range.end(); x != end; ++x)
			{
				const auto entity = osm_elements[x];

				switch (entity->type())
				{
				case osmium::item_type::node:
				{
					NodeCount++;
					break;
				}
				case osmium::item_type::way:
				{
					
					HighWay *highway = ht.getHighway(static_cast<const osmium::Way &>(*entity));
					if (highway != nullptr)
					{
						HighwayCount++;
						delete highway;
					}
					WayCount++;
					break;
				}
				case osmium::item_type::relation:
					RelationCount++;
					break;
				default:
					break;
				}
			}
		});
	}
	reader.close();

	high_resolution_clock::time_point t2 = high_resolution_clock::now();
	int64_t duration = std::chrono::duration_cast<std::chrono::milliseconds>(t2 - t1).count();

	std::cout << "File " << fileName << " has the following amounts of matching primitives:\n";
	std::cout << "Nodes: " << NodeCount << "\n";
	std::cout << "Ways: " << WayCount << "\n";
	std::cout << "Relations: " << RelationCount << "\n";
	std::cout << "Highways: " << HighwayCount << "\n";
	std::cout << "Node poi: " << NodePoiCount << "\n";
	std::cout << "Way poi: " << WayPoiCount << "\n";

	std::cout << "Parsing finished in " << duration << " ms" << std::endl;
}

```

**Comment by BergWerkGIS** [comment]
After changing 

```cpp
static_cast_with_assert<off_t>
```

to

```cpp
static_cast_with_assert<size_t>
```

`create_node_cache.exe monaco-latest.osm.pbf monaco.cache` succeeded but the cache file was 33GB.

Is this expected?
`300KB pbf` -> `33GB` cache file?

**Comment by joto** [comment]
@brano543 Please use this issue only for tracking the `off_t` problem. Start new issues if you have other problems. Otherwise it gets too confusing.

**Comment by joto** [comment]
@BergWerkGIS I commited a fix to master. Could you verify that this works. And yes, 33GB file is expected. See my first comment in this issue.

@brano543 This should fix the problem for you. But it will still generate this 33GB file which can take a while. I think your fix would have worked if you had given it more time.

**Comment by brano543** [comment]
@joto Good job. I will look around if there is some better solution for arbitrary input size. I think RocksDB may be a good candidate since the OSM data is read in already sorted order. I will keep you posted when i have done the testing.

**Comment by joto** [comment]
@brano543 As I mentioned, *SparseFileArray* works fine for small files. Or, if there is enough memory, *SparseMemArray* is even better and faster, because everything is in memory. Libosmium already has all the options for different file sizes, no need to roll your own.

**Comment by brano543** [comment]
@joto Btw why the index also takes into account negative ID´s when according to official Openstreetmap docs there are only positive ID´s?

Reference:
http://wiki.openstreetmap.org/wiki/Node

**Comment by BergWerkGIS** [comment]
@joto your latest changes to master work for me - no crash. From my point of view this issue can be closed.

> And yes, 33GB file is expected. See my first comment in this issue.

Sorry for asking the obvious - I read it, but somehow didn't get it.
