### ISSUE TITLE
avoid overhead of strftime?

### ISSUE THREAD

**Issue by springmeyer** [osmcode/libosmium#16]
`strftime` is accounting for many calls. This profiling output is from OS X when running the https://github.com/springmeyer/node-osmium tests:

![screen shot 2013-08-27 at 12 27 48 pm](https://f.cloud.github.com/assets/20300/1037419/15af8a36-0f4f-11e3-9bb8-c2888902656d.png)

**Comment by springmeyer** [comment]
perhaps resolved by https://github.com/osmcode/libosmium/commit/cf854e9c9f16416b4f5cb1845868636b06a27817

**Comment by joto** [comment]
@springmeyer no, this is the other direction, parsing the timestamp instead of writing it.
