### ISSUE TITLE
"Area contains no rings" when area has duplicate rings

### ISSUE THREAD

**Issue by woodpeck** [osmcode/libosmium#161]
Libosmium (as of commit 1d2caab011811ae8243bac326c5445d8a5d8bf47) fails to build this polygon

http://www.openstreetmap.org/relation/5515098

![Screenshot](http://www.remote.org/frederik/tmp/norings.png)

claiming that "area contains no rings".

It would be nice if the polygon could be built, or failing that, if the error message could be more precise - this polygon doesn't have no rings, it has too many.

**Comment by joto** [comment]
The reason for this is that the algorithm in osmium removes duplicate segments, which often fixes broken polygons. But in this case this is obviously not the right thing to do. Have to think about this one.

**Comment by joto** [comment]
Instead of "area contains no rings", this is now reported more generically as "invalid area" and the problem reports should mark those duplicate segments.
