### ISSUE TITLE
Adding custom tags to an way based on its geolocation

### ISSUE THREAD

**Issue by pcumino** [osmcode/libosmium#172]
Hi!
@jcoupey, I wonder if you could show more details about your implementation. I believe my issue is very close to yours.

The tags shall be added to ways based on the location (latitude and longitude). The information comes from a JSON file which I can easily modify if neccessary. I need to insert may be set as in this list below:

[lat], [lon], [tag_value]
[lat], [lon], [tag_value]
...
[lat], [lon], [tag_value]
test/t/builder/test_attr.cpp is not clear how it works.
Is there any example file that shows details about how the osmium writes on .pbf ?

Do you have any suggestion?

Thanks

**Comment by jcoupey** [comment]
@pcumino Not sure exactly what details you need. The way a specific tag can be added using an `osmium::memory::Buffer` is already described back at #145.

> Is there any example file that shows details about how the osmium writes on .pbf ?

Check out `osmium::io::Writer` in the documentation and examples.

**Comment by joto** [comment]
I have just added two examples `osmium_create_pois` and `osmium_change_tags` that might help you getting started on creating and writing OSM data.
