### ISSUE TITLE
Pattern Matching for Reader

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#181]
It would be great to allow for lambda-dispatching on the reader for quick one-off handlers:

```c++
Reader r{planet, entities};

r.match([&] (Way)    { num_ways += 1: },
        []  (Node n) { print(n); });
```

Similar to the `.match` feature in https://github.com/mapbox/variant/pull/128 this can be done creating a overload set merging the lambdas into a handler and applying the handler behind the scenes.

See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0051r2.pdf for a `overload` std proposal.

**Comment by joto** [comment]
Something like this would be interesting. But I don't see it on the `Reader`. Maybe a free function that can take a `Reader` or a `Buffer`.

**Comment by daniel-j-h** [comment]
:bow:

**Comment by mloskot** [comment]
Thanks!
