### ISSUE TITLE
Makefile should build in parallel by default

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/libosmium#184]
Invoking `make` should build translation units in parallel (think: `make -j $(nproc)`).

It does not at the moment:

https://github.com/osmcode/libosmium/blob/ccaab086d46c8298f8b57d443cd2779e7573f0c9/Makefile

Is there a reason for this @joto?

(Just stumbled upon this, called `make`, went for a coffee and it was still running when I came back)

**Comment by joto** [comment]
The "wrapper" Makefile shouldn't really be there. Instead people should use CMake directly, so they can set all options etc.

**Comment by joto** [comment]
I have removed the Makefile in 76e153d2c72bbc6472a7a408bd1f5c7157330c1c.
