### ISSUE TITLE
Check order handler fails on sorted history OSM file

### ISSUE THREAD

**Issue by buma** [osmcode/libosmium#188]
I sorted history OSM file and if I print all the node/way/relation they are sorted. But if I run it with check_order handler I get error that "Node IDs out of order". I assume this is since this is history file there are multiple versions with same ID and this check `if (m_max_node_id >= node.id()) {` is true since m_max_node_id is the same as node.id() when ID appears twice. 

I don't know if check_order should be changed (because ID appearing twice is probably an error in normal file) or docs should be changed that check_order doesn't support history files or I am doing something wrong.

**Comment by joto** [comment]
This is the expected and documented behaviour. From the API doc: "IDs have to be unique for each type." I will extent the documenation to make this more clear.
