### ISSUE TITLE
Posix functions

### ISSUE THREAD

**Issue by isowanderer** [osmcode/libosmium#191]
Hi,
I have tried to compile the libosmium library  on Windows OS (Visual Studio 2015, Windows 7) and I got  error messeges, that Posix functions are depricated:
"Error C4996	'read': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _read. See online help for details."
in read_write.hpp and compression.hpp files.

So the Posix functions 'open', 'close', 'read', 'write' are deprecated in Windows SDK.

Compiling invironment: Windows 7, x64, Visual Studio 2015, project platform x64.

**Comment by joto** [comment]
I already have lots of wrapper functions and `#ifdef`s to accommodate Windows and don't want to create more and more. Is there a way to turn those errors into warnings and then ignore them? :-)

**Comment by isowanderer** [comment]
I didn't find the way. I solved the problem with #ifdef.

**Comment by joto** [comment]
We are doing Windows compiles on Appveyor automatically and they don't have this problem. Can you have a look at https://github.com/osmcode/libosmium/blob/master/appveyor.yml, https://github.com/osmcode/libosmium/blob/master/build-appveyor.bat, and https://github.com/osmcode/libosmium/blob/master/build-local.bat and the resulting appveyor runs at https://ci.appveyor.com/project/Mapbox/libosmium and try to figure out what's different between your setup and the appveyor setup?

**Comment by joto** [comment]
Closing this, because there is no response. Please re-open if you want to pursue this further.
