### ISSUE TITLE
io.h header file 

### ISSUE THREAD

**Issue by isowanderer** [osmcode/libosmium#192]
Hi,

the io.h file  of SDK, that is included in read_write.hpp file, is covered with header file (io.h) in order \windows-builds\packages\geos\include\geos 

Compiling invironment: Windows 7, x64, Visual Studio 2015, project platform x64.

**Comment by joto** [comment]
Sorry, I don't understand what you are asking here? Can you try to elaborate?

**Comment by isowanderer** [comment]
I get the error message by compiling: 

Fehler	C3861	"_setmode": Bezeichner wurde nicht gefunden.		d:\builds\windows-builds\packages\libosmium\include\osmium\io\detail\read_write.hpp	 87	

although the <io.h> header file is included.

**Comment by BergWerkGIS** [comment]
@isowanderer could you verify if there several `io.h`s on your include path?
See the accepted solution here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/6dda2264-ae01-4010-8cc0-b50bc937417b/setmode-visual-studio-2008-c?forum=vcgeneral

**Comment by joto** [comment]
Closing this now, please re-open if this didn't fix it for you.
