### ISSUE TITLE
Fails to build with GCC 7

### ISSUE THREAD

**Issue by sebastic** [osmcode/libosmium#193]
As reported by Matthias Klose in [Debian Bug #853500](https://bugs.debian.org/853500):
> The package fails to build in a test rebuild on at least amd64 with
> gcc-7/g++-7, but succeeds to build with gcc-6/g++-6. The
> severity of this report may be raised before the buster release.
> There is no need to fix this issue in time for the stretch release.
>
> The full build log can be found at:
> http://people.debian.org/~doko/logs/gcc7-20170126/libosmium_2.11.0-1_unstable_gcc7.log
> The last lines of the build log are at the end of this report.
>
> To build with GCC 7, either set CC=gcc-7 CXX=g++-7 explicitly,
> or install the gcc, g++, gfortran, ... packages from experimental.
>
>   apt-get -t experimental install g++
>
> Common build failures are new warnings resulting in build failures with
> -Werror turned on, or new/dropped symbols in Debian symbols files.
> For other C/C++ related build failures see the porting guide at
> http://gcc.gnu.org/gcc-7/porting_to.html
>
> ```
> [...]
> 66: Test timeout computed to be: 9.99988e+06
> 66: Pass 1...
> 66: Pass 1 done
> 66: Pass 2...
> 66:   8.8721, 53.0966 post_office   
> 66: Pass 2 done
> 66/68 Test #66: examples_amenity_list ....................   Passed    0.01 sec
> test 67
>       Start 67: examples_pub_names
>
> 67: Test command: /<<PKGBUILDDIR>>/build/examples/osmium_pub_names "/<<PKGBUILDDIR>>/test/examples/t/pub_names/pubs.osm"
> 67: Test timeout computed to be: 9.99988e+06
> 67: Im Holze
> 67/68 Test #67: examples_pub_names .......................   Passed    0.00 sec
> test 68
>       Start 68: examples_road_length
>
> 68: Test command: /<<PKGBUILDDIR>>/build/examples/osmium_road_length "/<<PKGBUILDDIR>>/test/examples/t/road_length/road.osm"
> 68: Test timeout computed to be: 9.99988e+06
> 68: Length: 0.405759 km
> 68/68 Test #68: examples_road_length .....................   Passed    0.00 sec
>
> 97% tests passed, 2 tests failed out of 68
>
> Label Time Summary:
> area       =   0.01 sec (2 tests)
> builder    =   0.01 sec (2 tests)
> fast       =   0.64 sec (65 tests)
> geom       =   0.24 sec (13 tests)
> index      =   0.18 sec (5 tests)
> io         =   0.12 sec (13 tests)
> memory     =   0.01 sec (4 tests)
> osm        =   0.04 sec (13 tests)
> tags       =   0.01 sec (3 tests)
> thread     =   0.01 sec (1 test)
> unit       =   0.64 sec (65 tests)
> util       =   0.02 sec (9 tests)
>
> Total Test time (real) =   0.68 sec
>
> The following tests FAILED:
>        25 - geom_test_factory_with_projection (Failed)
>        34 - geom_test_wkt (Failed)
> Errors while running CTest
> debian/rules:27: recipe for target 'override_dh_auto_test-arch' failed
> make[1]: *** [override_dh_auto_test-arch] Error 8
> make[1]: Leaving directory '/<<PKGBUILDDIR>>'
> debian/rules:11: recipe for target 'build' failed
> make: *** [build] Error 2
> dpkg-buildpackage: error: debian/rules build gave error exit status 2
> ```

**Comment by sebastic** [comment]
Full build log: [libosmium_2.11.0-1_unstable_gcc7.txt](https://github.com/osmcode/libosmium/files/742788/libosmium_2.11.0-1_unstable_gcc7.txt)

Test failures from the build log:
```
test 25
      Start 25: geom_test_factory_with_projection

25: Test command: /<<PKGBUILDDIR>>/build/test/geom_test_factory_with_projection
25: Environment variables:
25:  OSMIUM_TEST_DATA_DIR=/<<PKGBUILDDIR>>/test
25: Test timeout computed to be: 9.99988e+06
25:
25: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
25: geom_test_factory_with_projection is a Catch v1.5.9 host application.
25: Run with -? for options
25:
25: -------------------------------------------------------------------------------
25: Projection using MercatorProjection class to WKT
25: -------------------------------------------------------------------------------
25: /<<PKGBUILDDIR>>/test/t/geom/test_factory_with_projection.cpp:8
25: ...............................................................................
25:
25: /<<PKGBUILDDIR>>/test/t/geom/test_factory_with_projection.cpp:12: FAILED:
25:   REQUIRE( wkt == "POINT(356222.37 467961.14)" )
25: with expansion:
25:   "POINT(356222.37
25:
25:
25:
25:  467961.14
25:
25:
25:
25: )"
25:   ==
25:   "POINT(356222.37 467961.14)"
25:
25: ===============================================================================
25: test cases: 2 | 1 passed | 1 failed
25: assertions: 2 | 1 passed | 1 failed
25:
25/68 Test #25: geom_test_factory_with_projection ........***Failed    0.00 sec
```
```
test 34
      Start 34: geom_test_wkt

34: Test command: /<<PKGBUILDDIR>>/build/test/geom_test_wkt
34: Environment variables:
34:  OSMIUM_TEST_DATA_DIR=/<<PKGBUILDDIR>>/test
34: Test timeout computed to be: 9.99988e+06
34:
34: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
34: geom_test_wkt is a Catch v1.5.9 host application.
34: Run with -? for options
34:
34: -------------------------------------------------------------------------------
34: WKT geometry for point in ekwt in web mercator
34: -------------------------------------------------------------------------------
34: /<<PKGBUILDDIR>>/test/t/geom/test_wkt.cpp:31
34: ...............................................................................
34:
34: /<<PKGBUILDDIR>>/test/t/geom/test_wkt.cpp:35: FAILED:
34:   REQUIRE( wkt == "SRID=3857;POINT(356222.37 467961.14)" )
34: with expansion:
34:   "SRID=3857;POINT(356222.37
34: <88><97>± 467961.14
34: 9<9a>±)"
34:   ==
34:   "SRID=3857;POINT(356222.37 467961.14)"
34:
34: ===============================================================================
34: test cases:  4 |  3 passed | 1 failed
34: assertions: 22 | 21 passed | 1 failed
34:
34/68 Test #34: geom_test_wkt ............................***Failed    0.00 sec
```

**Comment by joto** [comment]
I can not reproduce this problem on a Debian unstable with gcc-7 from experimental.

**Comment by sebastic** [comment]
Neither can I now, sorry for the noise.
