### ISSUE TITLE
Using area assembler without evaluating tags

### ISSUE THREAD

**Issue by lonvia** [osmcode/libosmium#194]
For osm2pgsql we plan to switch from geos to libosmium for creating polygons. libosmium's area assembler is doing a good job but is actually doing too much for us as it is also evaluating tags. That might interfere with osm2pgsql's own tag evaluation. We actually need a function that just assembles areas from ways and relations if anyhow possible.

To solve that, I've added two functions to the area assembler that achieve exactly that:

```
bool make_area(const osmium::Way &way, osmium::memory::Buffer &out_buffer) {
    m_segment_list.extract_segments_from_way(m_config.problem_reporter, way, true);

    if (!create_rings()) {
        return false;
    }

    osmium::builder::AreaBuilder builder{out_buffer};
    builder.initialize_from_object(way);
    add_rings_to_area(builder);
    out_buffer.commit();
    return true;
}

bool make_area(const osmium::Relation &relation, osmium::memory::Buffer const &ways, osmium::memory::Buffer &out_buffer)
{
    for (auto const &w : ways.select<osmium::Way>()) {
        m_segment_list.extract_segments_from_way(m_config.problem_reporter, w, true);
    }

    if (!create_rings()) {
        return false;
    }

    osmium::builder::AreaBuilder builder{out_buffer};
    builder.initialize_from_object(relation);
    add_rings_to_area(builder);
    out_buffer.commit();
    return true;
}
```

That's working okay and I'd like to see something like this go into libosmium master. However, this particular implementation is specifically geared towards our use case. A different way to go about that, is to make a few functions public, so that the area assembler can be used with arbitrary input data. Given the code above, we'd need only three functions to be publicly accessible:

  * extract segments from way
  * create rings
  * add rings to area

I can provide PRs for both solutions if that helps. Any preferences?

For reference, the current state of the geometry assembly rewrite can be found [here](https://github.com/lonvia/osm2pgsql/tree/projection-in-output).

**Comment by lonvia** [comment]
The split-assembler branch works for me and passes the osm2pgsql tests.

**Comment by joto** [comment]
I have merged the split-assembler branch now.
