### ISSUE TITLE
Handling of invalid locations in area assembler

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#195]
Currently the area assembler expects all locations in the ways it uses to create a (multi)polygon to be valid. If a location is not valid, the result is not well defined. In most cases it will probably just fail to create the multipolygon, but it could also create totally broken ones.

This is most certainly something we want to fix. The assembler should either throw an exception or just not try to build any area. Other failures in the data are handled by the assembler by not building any area (and possibly reporting the error throw a "problem_reporter"), so I tend towards using the same mechanism here also.

This came up in the context of https://github.com/openstreetmap/osm2pgsql/pull/684 . osm2pgsql wants to be able to handle the case of invalid locations by just ignoring those locations and trying to build an area from the remaining valid locations. This could help at the boundary of an extract. I do not think this is the right solution, though, because it could lead to wrong polygons like in this example:

![ignore-invalid-locations-area](https://cloud.githubusercontent.com/assets/113756/22777631/1f6cd798-eeb4-11e6-9fe6-87c18fcbf412.png)

Ignoring all locations outside the dotted box would create a triangular polygon exactly where the original polygon is not!

/cc @lonvia @pnorman

**Comment by pnorman** [comment]
> osm2pgsql wants to be able to handle the case of invalid locations by just ignoring those locations and trying to build an area from the remaining valid locations. This could help at the boundary of an extract. I do not think this is the right solution, though, because it could lead to wrong polygons like in this example

Do we? I don't think that's current behavior.

**Comment by lonvia** [comment]
See for example: https://github.com/openstreetmap/osm2pgsql/blob/master/middle-pgsql.cpp#L354

**Comment by lonvia** [comment]
We actually make use of the feature for rendering the Swiss map on http://osm.ch. The extract is created from a padded Swiss polygon with excat cutting (only nodes inside the polygon). The rendered map has the landcover roughly follow the extract polygon, so it's a cheap way to get a cut-out-effect. It's far from perfect, there are [smaller rendering errors](http://osm.ch/#16/47.5218/6.9022) and sometimes [missing areas](http://osm.ch/#14/47.8506/8.4938) where a multipolygon is now incomplete. So I would be in favour of keeping the current behaviour and just skipping over the missing nodes. For those who prefer to render the full polygons on extract boundaries, extracts with the complete way option or osmium smart extracts can be used.

**Comment by joto** [comment]
I have added support for ignoring invalid locations in 3459e8484e727decfe6e686e8cff18a3d56dce6c.
