### ISSUE TITLE
Infinite loop in osmium::memory::Buffer::reserve_space

### ISSUE THREAD

**Issue by botanegg** [osmcode/libosmium#202]
I catch an inf loop by simple code using `Buffer(size_t capacity, auto_grow auto_grow = auto_grow::yes)` [ctor](https://github.com/osmcode/libosmium/blob/f11106d3af727a2642fe06a427b3e6e11d0b9ea0/include/osmium/memory/buffer.hpp#L200)

```
    // reproducing code
    osmium::memory::Buffer node_buffer{0, osmium::memory::Buffer::auto_grow::yes};
    osmium::builder::NodeBuilder builder{node_buffer};
```
`Buffer(size_t capacity, auto_grow auto_grow = auto_grow::yes)` uses `new unsigned char[capacity]` and set m_memory to non-null (that is "valid buffer"), however m_capacity is 0;
Because m_capacity is 0 [reserve_space](https://github.com/osmcode/libosmium/blob/f11106d3af727a2642fe06a427b3e6e11d0b9ea0/include/osmium/memory/buffer.hpp#L452) is infinite:
```
                        size_t new_capacity = m_capacity * 2;
                        while (m_written + size > new_capacity) {
                            new_capacity *= 2;
                        }
```
Simple fixing `m_memory(capacity ? new unsigned char[capacity] : nullptr)` leads to [assertion](https://github.com/osmcode/libosmium/blob/f11106d3af727a2642fe06a427b3e6e11d0b9ea0/include/osmium/memory/buffer.hpp#L443)

**Comment by joto** [comment]
Looks like I didn't expect anybody to choose a zero capacity. This is fixed in 7685449e by using a minimum capacity for the buffer. If you don't want to switch, you can use a non-zero capacity yourself.

**Comment by botanegg** [comment]
Were there any reason to use a growth factor = 2 rather than 1.5 as an example here https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md#memory-handling

**Comment by joto** [comment]
@botanegg I didn't think too much about it. The reasoning in [FBVector.md](https://github.com/facebook/folly/blob/master/folly/docs/FBVector.md#memory-handling) is interesting, but I don't think it is particularly important. You don't just allocate one vector/buffer and keep it around a long time, but a typical program will have many of them being allocated and deallocated, etc. So memory can just be reused for something else. Maybe somebody wants to benchmark this?
