### ISSUE TITLE
Generating llvm byte code

### ISSUE THREAD

**Issue by kepta** [osmcode/libosmium#203]
I am new to C++ code compilation, but needed help with building libosmium to llvm byte code.
Is there a way to do it?

**Comment by springmeyer** [comment]
@kepta can you say more about why you are interested in compiling libosmium in this way?

**Comment by kepta** [comment]
@springmeyer I want to use [emscripten](https://github.com/kripken/emscripten) for a high performance asm.js / WASM port of this library. I really don't know the feasibility of such a stunt though. 
Would love to hear your opinion.

**Comment by joto** [comment]
@kepta Libosmium uses multithreading. I don't think that will work in asm.js.
