### ISSUE TITLE
profiling of pbf parsing

### ISSUE THREAD

**Issue by springmeyer** [osmcode/libosmium#21]
Ticket to track ideas around optimizing threaded pbf parsing.

Unclear how much this impacts linux, but at least on OS X we are seeing `std::vector<unsigned char>` allocation taking a surprising amount of time:

![screen shot 2013-12-13 at 8 20 33 am](https://f.cloud.github.com/assets/20300/1743898/14adeece-6414-11e3-8b3c-e821b2a03ab8.png)

**Comment by joto** [comment]
The PBF implementation has totally changed, so this is not useful any more.
