### ISSUE TITLE
Coverity code scan findings

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#218]
I ran Coverity Code Scans on a [project with libosmium dependencies](https://scan.coverity.com/projects/mmd-osm-overpass-api?tab=overview) and found a few potential issues related to libosmium.

As always code analysis results should be taken with a grain of salt, some of the issues below are probably false alerts. In theory you should be able to access those results via the project link above. For reference, I have also added a few screenshots below.

btw: it might be worthwhile setting this up on your own as part of a continuous integration toolchain via Travis CI. The [Coverity website](https://scan.coverity.com/) has some further details on this.

![grafik](https://user-images.githubusercontent.com/5842757/28995240-6af13b80-79e4-11e7-86eb-5aa8be4897d1.png)

![grafik](https://user-images.githubusercontent.com/5842757/28995243-82c9cfa6-79e4-11e7-93e3-af9a91f376b6.png)

![grafik](https://user-images.githubusercontent.com/5842757/28995219-a2eb7b6e-79e3-11e7-8dab-e7ca9d06b75f.png)

Uncaught Exception:

![grafik](https://user-images.githubusercontent.com/5842757/28995227-f25e58c4-79e3-11e7-8b42-d90b621c7ea8.png)

![grafik](https://user-images.githubusercontent.com/5842757/28995230-123e0310-79e4-11e7-9e7e-79456d384b73.png)

![grafik](https://user-images.githubusercontent.com/5842757/28995236-4f94da5e-79e4-11e7-894a-b3fc804b2a0c.png)

![grafik](https://user-images.githubusercontent.com/5842757/28995239-5c69dc20-79e4-11e7-8065-84dafefbe977.png)

**Comment by joto** [comment]
These are all false positives.

* Only because something still has a pointer to something that is destroyed doesn't mean it will actually use that pointer. `m_bzstream.next_out` is only used in `BZ2_bzDecompress()`.
* Objects of `Changeset` class are always created through `ChangesetBuilder` which sets the `user_size`.
* `add_padding()` can not throw, because buffers are allocated in a way that there is always enough memory for the padding.

**Comment by mmd-osm** [comment]
Thank you for the feedback. Yes, I thought so, though I wanted to make you aware that there are tools out there reporting some potential issues.

Regarding the first issue, `m_bzstream.next_out` has a longer lifetime than output.data() and probably still lingers around when read() method finishes in whatever state `BZ2_bzDecompress()` left it here. In theory, another method could try to use that buffer in `m_bzstream` at a later point in time when it's no longer valid. Method `close()`  calling `BZ2_bzDecompressEnd(&m_bzstream);` would come to mind, although implementation specifics are probably different in that case.

**Comment by joto** [comment]
Frankly I don't like applications that require me to login to even see things and when you login require rights they don't need. I don't mind if you or somebody else runs those applications though.

**Comment by mmd-osm** [comment]
Someone from synopsis, the vendor providing coverity, contacted me with the following request: 

> Before we can approve your project’s submission into SCAN, we need proof that you are a contributor to the upstream project. This requirement is necessary for our responsible disclosure policy.

As Github won't list me as "Contributor", I won't be able to access scan results. If you feel still positive about running those apps, I would mention that to synopsis.

**Comment by joto** [comment]
@mmd-osm I am not sure what this means. You can already see those defects, can't you? Can't anybody see the results who is willing to login to coverity?

**Comment by mmd-osm** [comment]
Oh, I think I forgot to add a bit of more context. So far, I included libosmium in my Overpass API branch and ran coverity on the whole project. I added some of those results to this issue.

Now, to get a better coverage (I only used a rather small part of libosmium with Overpass), I thought to run the whole libosmium make process through the code scan. For the latter, I had to request access, which hasn't been granted yet. The "View Defects" link for libosmium is still inactive:

![grafik](https://user-images.githubusercontent.com/5842757/29279370-d8919524-8117-11e7-90aa-76c7e5853e5b.png)

**Comment by joto** [comment]
Ah, okay. That makes more sense now. It also means that everbody can just create a project, include libosmium and then run all the checks they want. So why don't you just do that and then you don't have to ask for any permissions? :-)

**Comment by mmd-osm** [comment]
Pinged @coverity again with regards to the project approval status, since there hasn't been a response to my email since more than a month now.

**Comment by mmd-osm** [comment]
I'm closing this one due to lack of feedback from @coverity side.
