### ISSUE TITLE
Invalid_location in Way-Handler-Example with WayNodes

### ISSUE THREAD

**Issue by HerrKlemmy** [osmcode/libosmium#219]
Hi there, here a new issue for my wrong ones ([here as comment](https://github.com/osmcode/libosmium/issues/142), [and here](https://github.com/osmcode/osmcode.github.io/issues/6) - @joto Freue mich über deine Hilfe).

I´ve got the complete example Way-Node-Handler from the [manual](http://osmcode.org/libosmium/manual.html#handlers):

```c++
class WayNodeHandler : public osmium::handler::Handler {
public:
    void way(const osmium::Way& way) {
        for (const auto& n : way.nodes()) {
            // [...]
        }
    }
};

list<string> routeCalculator::calculateRoute(Location start, Location destination) {
    // aus der osm-Datei Nodes und Ways filtern
    auto otypes = osmium::osm_entity_bits::node | osmium::osm_entity_bits::way;
    osmium::io::Reader reader{"lib/osm_files/industriegebietKastelKlein.osm", otypes};

    namespace map = osmium::index::map;
    using index_type = map::SparseMemArray<osmium::unsigned_object_id_type, osmium::Location>;
    using location_handler_type = osmium::handler::NodeLocationsForWays<index_type>;
    index_type index;
    location_handler_type location_handler{index};
    location_handler.ignore_errors();

    WayNodeHandler handler;
    osmium::apply(reader, location_handler, handler);


    reader.close();
    list<string> listOfRoutes;
    listOfRoutes.push_back("Läuft");
    return listOfRoutes;
}
```

and all the necessary includes, but everytime, whatever inputfile I use, it ends with an location_invalid-Error.

`libc++abi.dylib: terminating with uncaught exception of type osmium::invalid_location: invalid location`

The idea to ignore that error with location_handler.ignore_errors(); as noted above didn't help.

To catch this error in the handler also didn't work.

Also what I noticed is, that this error occurs at the end of the osm file. 
It seems that the handler tries to read another node, but there isn't one.
I noticed that, while I printed every way-node in the for-loop like this:

```c++
for (const auto& n : way.nodes()) {
    cout << "Punkt:" << n.ref() << ": " << n.lon() << ", " << n.lat() << '\n';
}
```

all Nodes in the file are printed, but after the last one, the error occurs.
So the error is thrown for a Location, that doesn't exist...

What am I doing wrong for this is the whole example like on the manual? 
Help me please! :)

P.S. I hope that this time I did all right for this issue.

**Comment by joto** [comment]
First: Are you sure your input files have all nodes? Use `osmium check-refs file.osm` to check that.

Second: A quick look through your program, look okay. Can you post your whole program somewhere together with an input file, so I could run this myself?

**Comment by HerrKlemmy** [comment]
1. I couldn't install the osmium-command, but the file should be good. first because I exported it from the osm-webside and second, see 2. :/

2. I copied the code-parts into a new project and created a gist for you:
https://gist.github.com/HerrKlemmy/a487cf1656bd456e06638d26ba1b9262

But - I dont know why - this small version with the exact same code works...

**Comment by joto** [comment]
Not sure what I am supposed to do then with that code...

**Comment by HerrKlemmy** [comment]
me neither ^^

But do you have any idea, where my error could come from? 
I´m stuck, but i need this waynodes!!

**Comment by HerrKlemmy** [comment]
Ok, thank you for you help.
I now know, that somewhere something did collide with this example code.
I deleted lines and pasted the same again and now it works...

Coding at its best again.

I´m sorry for your lost time, but thankful for your ideas and help!
