### ISSUE TITLE
Multipolygons with touching inner rings

### ISSUE THREAD

**Issue by andreynovikov** [osmcode/libosmium#225]
As stated in http://wiki.openstreetmap.org/wiki/Relation:multipolygon#Touching_inner_rings this is the OSM exception from standard OGC Simple Features. I've noticed that a lot of multipolygons use this feature. And every day more and more of them appear (mostly forests and other very complicated areas). libosmium considers them as invalid. This results in maps created with the help of libosmium look not correctly.

**Comment by joto** [comment]
Osmium can usually handle this case. If you have specific examples that libosmium doesn't handle the way you think they should be handled, tell us. Also there were a lot of changes regarding multipolygon handling recently and there are different ways to create multipolyons with libosmium (different Assembler, Collector and Manager classes) and the version of libosmium you are using is also relevant.

**Comment by andreynovikov** [comment]
I'm using pyosmium, have now updated to 2.12.4 (installed from Debian unstable packages because pip3 install failed).

I use `wkbFactory.create_multipolygon(o)` to construct polygons. Retried my scripts after update and still get `invalid area` exceptions. Example relations:
https://www.openstreetmap.org/relation/7356538 - the simplest one
https://www.openstreetmap.org/relation/7360840
https://www.openstreetmap.org/relation/7401189
https://www.openstreetmap.org/relation/7411548

(No, I'm not the author of these changesets but I've checked with JOSM and iD editors: they all validate and are correctly rendered by OSM renderer.)

**Comment by joto** [comment]
This looks like cases of this here: https://github.com/osmlab/fixing-polygons-in-osm/issues/31 . Libosmium currently can't handle these and I am not sure what to do, I haven't thought through this completely. I encourage everybody to *not* map something like this. Even if this might be technically correct (and I am not convinced yet that we can have an iron-clad specification that explains how these cases are to be handled), this is extremly difficult for a mapper to understand. I think it would be better to split this up into smaller multipolygons.

**Comment by andreynovikov** [comment]
It's mostly that case but not exactly. In my examples `?` area is also defined as inner ring so there is no any fake hole.

As I understand inner rings are joined if they are touching each other. I my example all three inner rings should collapse into one.

**Comment by andreynovikov** [comment]
Just another complex multipolygon that produces error but renders nicely by CartoCSS:
http://www.openstreetmap.org/relation/6677807
