### ISSUE TITLE
Fails to build unless '-lexpat' is added to linker flags

### ISSUE THREAD

**Issue by schaiba** [osmcode/libosmium#231]
Compilation fails because the linker is not instructed to use libexpat. Ubuntu 16.04, 64-bit.

**Comment by joto** [comment]
Can you tell us which commands you were using exactly to compile what exactly?

**Comment by schaiba** [comment]
Per the docs, git clone, cd, mkdir build, cd build, cmake . , make.

**Comment by joto** [comment]
Just tested this on Ubuntu 16.04 and it works fine. Is libexpat installed? Can you post the log from the build?

**Comment by schaiba** [comment]
It's installed, and if I add -lexpat it compiles just fine. I'll add the log.
