### ISSUE TITLE
osmium craches with gdb

### ISSUE THREAD

**Issue by MichalPP** [osmcode/libosmium#235]
where I try to run `osmium tags-filter planet-latest.osm.pbf wr/highway=path -o highways.pbf` (osmium-tool v1.7.1-1), it works fine.
however, when I run the same command from gdb or run `osrm-extract -p oma-car.lua planet-latest.osm.pbf` ([see](https://github.com/Project-OSRM/osrm-backend/issues/4678), OSRM v5.12 - this one says it's out of memory) libosmium fails with

```Thread 5 "_osmium_pbf_in" hit Catchpoint 1 (exception thrown), 0x00007ffff6ff1bad in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6```
bt is
```#0  0x00007ffff6ff1bad in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00005555555d430f in osmium::io::detail::PBFParser::read_from_input_queue[abi:cxx11](unsigned long) ()
#2  0x00005555555d9d40 in osmium::io::detail::PBFParser::parse_data_blobs() ()
#3  0x00005555555e4e73 in osmium::io::detail::PBFParser::run() ()
#4  0x00005555555f95be in osmium::io::Reader::parser_thread(osmium::thread::Pool&, std::function<std::unique_ptr<osmium::io::detail::Parser, std::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> const&, osmium::thread::Queue<std::future<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osmium::thread::Queue<std::future<osmium::memory::Buffer> >&, std::promise<osmium::io::Header>&&, osmium::osm_entity_bits::type, osmium::io::read_meta) ()
#5  0x00005555555f26c9 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (*)(osmium::thread::Pool&, std::function<std::unique_ptr<osmium::io::detail::Parser, std::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> const&, osmium::thread::Queue<std::future<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osmium::thread::Queue<std::future<osmium::memory::Buffer> >&, std::promise<osmium::io::Header>&&, osmium::osm_entity_bits::type, osmium::io::read_meta), osmium::thread::Pool&, std::function<std::unique_ptr<osmium::io::detail::Parser, std::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)>&, osmium::thread::Queue<std::future<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, osmium::thread::Queue<std::future<osmium::memory::Buffer> >&, std::promise<osmium::io::Header>, osmium::osm_entity_bits::type, osmium::io::read_meta> > >::_M_run() ()
#6  0x00007ffff701c72f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff772a494 in start_thread (arg=0x7ffff4c9e700) at pthread_create.c:333
#8  0x00007ffff6792abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```
there is plenty of RAM (some 10GB still left at peak usage), SWAP is not touched at all. PBF file is the latest from planet.osm.org (36GB) or europe from geofabrik (20GB) or 4GB DACH or 8GB north america file from geofabrik. even small 200MB files fail (but osrm runs fine). I have latest debian testing. 

any hints?

**Comment by joto** [comment]
Found [this](https://sourceware.org/gdb/onlinedocs/gdb/Interrupted-System-Calls.html#Interrupted-System-Calls) in the GDB docs. Maybe it has something to do with interrupted system calls. I just committed a change that tries to handle this case, but I can not test it, because the problem you describe doesn't happen on my system. Please try the newest master and see whether that changes something.

If this doesn't help it would be good if you can find out which exception was thrown at that point.

**Comment by joto** [comment]
@MichalPP Anything new here?

**Comment by joto** [comment]
No feedback, so I am classifying this as a fixed bug and will close this issue now. Please reopen if there are still problems.

**Comment by MichalPP** [comment]
upgrade seems to solve it. sorry, my compiling skills are very low... thank you
