### ISSUE TITLE
Processing of route relations

### ISSUE THREAD

**Issue by andreynovikov** [osmcode/libosmium#236]
I need to extract pistes. [Many of them](https://taginfo.openstreetmap.org/tags/piste%3Atype=nordic) use relations as piste can go through highway, then through open area, then through highway and so on. As I see libosmium processes only multipolygon and boundary relations. Is not processing route relations intentional or a missing feature? Are there any plans for it?

**Comment by Nakaner** [comment]
There is no feature missing. I have implemented several relation managers for similar use cases in the last two years.

You have to write your own relation manager which collects the relations and their members you are interested in. See the [section](http://osmcode.org/libosmium/manual.html#using-the-relationsmanager) about writing your own relation manager in the Libosmium Manual.

I think this issue can be closed because it is neither a bug nor a missing feature.

**Comment by andreynovikov** [comment]
Thank you. In fact I'm using pyosmium for data processing. Does it mean I have to write my own Handler instead of SimpleHandler?

**Comment by joto** [comment]
@andreynovikov You'd have to first write a C++ manager for the relations and then tie this into pyosmium. This is not an easy task. The reasons something like this isn't built into libosmium/pyosmium (yet) is lack of time and, unlike multipolygons which have reasonably clear semantics, route relations have different variants (public transport, highways, hiking, ...) and users have different needs here.

In your case you can also just do everything "manually" by using the relation callback function in your own handler written in Python remembering all ways you need for this relation and then read the file again, reading all ways, checking to which relation they belong and do whatever you want to do with them. This isn't as fast as doing it in C++, but should be okay for your use case. Just one suggestion: Use something like [`osmium tags-filter`](http://docs.osmcode.org/osmium/latest/osmium-tags-filter.html) to first filter everything with the tags you are interested in which makes the data much smaller. Only then do the extra processing in Pyosmium. It will be much faster than trying to work on the whole planet in Pyosmium.

**Comment by andreynovikov** [comment]
Thank you. This is exactly how I do it now. But this approach requires writing specific pre-processors for different tasks, storing the data is some intermediate database and then combining it all together with general map data. This is what I wanted to get rid of.

In general it would be nice if pyosmium parser will have some means of specifying what members you are interested in from relation callback.

**Comment by joto** [comment]
This is really more a suggestion for pyosmium. Closing this here.
