### ISSUE TITLE
Build failures since protozero removal

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#238]
Since the recent removal of protozero libraries, I'm getting compilation errors now on Ubuntu 16.04 even with libprotozero-dev installed:

Tested on 89e634dfc3f1ec473abb66a5e2baec234a05ea1d. The code in question refers to https://github.com/mmd-osm/Overpass-API/tree/test758_lz4hash

```
  CXX      overpass_api/output_formats/output_popup.o
In file included from /home/mmd/libosmium/include/osmium/io/detail/pbf_output_format.hpp:39:0,
                 from /home/mmd/libosmium/include/osmium/io/pbf_output.hpp:45,
                 from ../src/overpass_api/output_formats/output_osmium.h:14,
                 from ../src/overpass_api/output_formats/output_osmium.cc:4:
/home/mmd/libosmium/include/osmium/io/detail/protobuf_tags.hpp:36:31: fatal error: protozero/types.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
ar: `u' modifier ignored since `D' is the default (see `U')
Makefile:1790: die Regel für Ziel „overpass_api/output_formats/output_osmium.o“ scheiterte
make[2]: *** [overpass_api/output_formats/output_osmium.o] Fehler 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
ar: `u' modifier ignored since `D' is the default (see `U')
In file included from /home/mmd/libosmium/include/osmium/io/detail/pbf_output_format.hpp:39:0,
                 from /home/mmd/libosmium/include/osmium/io/pbf_output.hpp:45,
                 from ../src/overpass_api/output_formats/output_osmium.h:14,
                 from ../src/overpass_api/output_formats/output_osmium_factory.cc:3:
/home/mmd/libosmium/include/osmium/io/detail/protobuf_tags.hpp:36:31: fatal error: protozero/types.hpp: Datei oder Verzeichnis nicht gefunden
compilation terminated.
Makefile:1790: die Regel für Ziel „overpass_api/output_formats/output_osmium_factory.o“ scheiterte

```

**Comment by joto** [comment]
Libprotobuf hasn't been used in libosmium in ages. What you probably mean is that the included `protozero` has been removed. Simply install protozero first like you would any other external library and you should be good to go.

**Comment by mmd-osm** [comment]
Right, I meant protozero. I'm currently following the updated instructions on http://osmcode.org/libosmium/manual.html#dependencies:

--> 

Protozero (since version 2.3.0)

 Up to version 2.13 a copy of this library was included in the libosmium repository. For newer version you need to install either a packaged version or a version from the git repository.

    Debian/Ubuntu: libprotozero-dev
    Fedora: protozero-devel

So, I did install libprotozero-dev as described, but there's no protozero/types.hpp available...

**Comment by joto** [comment]
The package in Ubuntu 16.04 is too old. Either install from Debian backports or from the github repository.

**Comment by mmd-osm** [comment]
Ok, that's a bit unfortunate, as 16.04 will be around for a few more years. I guess the best option for this release would be to just use `libosmium2-dev` package instead.

Could you please also update the documentation on osmcode.org with some additional information about supported / required libprotozero-dev versions. Also a link to the git repository would be helpful. I've seen that you've referenced some mapbox repo in your Travis CI scripts, but it's not clear to me if this is the right one.

**Comment by joto** [comment]
The documentation isn't perfect, but http://osmcode.org/libosmium/manual.html#dependencies has the link. You don't need to stick with old versions, just check out the protozero repository next to the libosmium repository (both git clones in the same directory) and libosmium will find it.

**Comment by joto** [comment]
I have added some information to the manual to hopefully make this clearer.

**Comment by mmd-osm** [comment]
Thanks! 

BTW: I started adding libosmium and protozero as submodules in another project. This way git can automatically pull the correct commit for each repo via `git submodule update --init --recursive`. 

https://github.com/mmd-osm/Overpass-API/tree/test758_lz4hash/src/third_party
