### ISSUE TITLE
cmake .. 出错

### ISSUE THREAD

**Issue by lytk01** [osmcode/libosmium#240]
Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Looking for doxygen - not found
--   Disabled making of documentation.
-- Configuring documentation - done
-- Looking for clang-tidy
-- Looking for clang-tidy - not found
--   Build target 'clang-tidy' will not be available.
-- Configuring incomplete, errors occurred!
See also "/libosmium/build/CMakeFiles/CMakeOutput.log".
See also "/libosmium/build/CMakeFiles/CMakeError.log".

**Comment by joto** [comment]
Sorry, I can't do anything with this report. If you want help from us here, clearly state
* what you were trying to achieve,
* what you did,
* what you expected to happen and
* what happened instead.
