### ISSUE TITLE
decimal place accuracy of nodes

### ISSUE THREAD

**Issue by CraigglesO** [osmcode/libosmium#244]
Hello! Thanks for this library! It's great! When I look at longitudes and latitudes I get decimal place accuracy of 4 for lat and 3 for lon:
`lat: 41.1337 lon: -111.766`

Is this normal?

When I use a NodeJS equivalent reader, I get accuracy of 7 decimal places which makes more sense to me.

Thanks,
Craig.

**Comment by joto** [comment]
Libosmium uses the max accuracy that OSM locations have, ie 7 digits after the decimal point.

You don't tell us how you get the results that you got, but I suspect you are using C++ streams output which has 6 digits default precision (6 digits before and after decimal point together). See http://en.cppreference.com/w/cpp/io/ios_base/precision .

**Comment by CraigglesO** [comment]
Yeah -_- sorry I didn't know that streams cripple precision.
Thanks for your help.
