### ISSUE TITLE
Differentiating between anonymous user and userid not set

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#249]
Osmium uses the same internal value (`0`) whether a uid was not set at all and for the anonymous user. Is differentiating this important enough that we should change this in some way. Some programs use `-1` as the value for "not set". We didn't do this originally because we then would need a signed type for the user id, throwing away half the number space just for this one value. We can't change the underlying type now, because we want to stay backwards compatible, but we could reserve a special value (MAXINT probably) as the "not set" value. This could still be a problem somewhere.

Does Osmosis even differentiate between "not set" and "anonymous user"?

/cc @Nakaner

**Comment by mmd-osm** [comment]
> Does Osmosis even differentiate between "not set" and "anonymous user"?

It seems like Osmosis uses -1 for "not set": https://github.com/openstreetmap/osmosis/blob/master/osmosis-core/src/main/java/org/openstreetmap/osmosis/core/domain/v0_6/OsmUser.java#L29

**Comment by joto** [comment]
Okay, we'll leave it as it is then.
