### ISSUE TITLE
osmium_count core dump if called with --help option

### ISSUE THREAD

**Issue by wosch** [osmcode/libosmium#257]
Most tools in ~/libosmium/build/examples support the -h or --help options. However, some crash with a core dump:

./osmium_count --help
terminate called after throwing an instance of 'osmium::io_error'
  what():  Could not detect file format for filename '--help'.
Aborted (core dumped)

**Comment by wosch** [comment]
the list of tools which crash with the --help option:

osmium_amenity_list
osmium_count
osmium_debug
osmium_pub_names
osmium_read
osmium_read_with_progress
osmium_road_length

**Comment by joto** [comment]
These are example programs that are intentionally kept simple to show how Osmium can be used without the distractions of real error checking etc.
