### ISSUE TITLE
regression on handling of valid multipolygons

### ISSUE THREAD

**Issue by woodpeck** [osmcode/libosmium#258]
Commit 3ad4e297983a8b08dc1653d0e40aeb75a361419d has broken the handling of valid inner rings in new-style multipolygons. Consider this simple test file that has a forest with a hole consisting of farmland:

````
<osm version="0.6">
 <node id="1" lat="10" lon="10"/>
 <node id="2" lat="10" lon="0"/>
 <node id="3" lat="0" lon="0"/>
 <node id="4" lat="0" lon="10"/>
 <node id="11" lat="5" lon="5"/>
 <node id="12" lat="5" lon="4"/>
 <node id="13" lat="4" lon="4"/>
 <node id="14" lat="4" lon="5"/>
 <way id="1">
  <nd ref="1"/>
  <nd ref="2"/>
  <nd ref="3"/>
  <nd ref="4"/>
  <nd ref="1"/>
 </way>
 <way id="2">
  <nd ref="11"/>
  <nd ref="12"/>
  <nd ref="13"/>
  <nd ref="14"/>
  <nd ref="11"/>
  <tag k="landuse" v="farmland"/>
 </way>
 <relation id="1">
  <member type="way" ref="1" role="outer"/>
  <member type="way" ref="2" role="inner"/>
  <tag k="natural" v="wood"/>
  <tag k="type" v="multipolygon"/>
 </relation>
</osm>
````
The *expected* output of this, when run through e.g. osmium_area_test -o, is two polygons - a forest with a hole, and a farmland. Like this (slightly shortened):
````
AREA: [240]
  id=3
  TAGS: [21]
    k=|natural| v=|wood|
  OUTER RING: [88]
    ref=3 pos=(0,0)
    ref=4 pos=(10,0)
    ref=1 pos=(10,10)
    ref=2 pos=(0,10)
    ref=3 pos=(0,0)
  INNER RING: [88]
    ref=13 pos=(4,4)
    ref=12 pos=(4,5)
    ref=11 pos=(5,5)
    ref=14 pos=(5,4)
    ref=13 pos=(4,4)
AREA: [160]
  id=4
  TAGS: [25]
    k=|landuse| v=|farmland|
  OUTER RING: [88]
    ref=13 pos=(4,4)
    ref=14 pos=(5,4)
    ref=11 pos=(5,5)
    ref=12 pos=(4,5)
    ref=13 pos=(4,4)
````
This works with all versions prior to the commit. After, and up until the current HEAD version at the time of submitting this ticket, we have this output (again, slightly shortened):
````
AREA: [240]
  id=3
  TAGS: [21]
    k=|natural| v=|wood|
  OUTER RING: [88]
    ref=3 pos=(0,0)
    ref=4 pos=(10,0)
    ref=1 pos=(10,10)
    ref=2 pos=(0,10)
    ref=3 pos=(0,0)
  INNER RING: [88]
    ref=13 pos=(4,4)
    ref=12 pos=(4,5)
    ref=11 pos=(5,5)
    ref=14 pos=(5,4)
    ref=13 pos=(4,4)
````
i.e. the separate farmland polygon is simply missing.

**Comment by joto** [comment]
The `osmium_area_test` program from the examples that you are using has a built-in filter for areas tagged `landuse=forest` or `natural=wood` only. This is why the closed way tagged `landuse=farmland` doesn't appear in its output. If you use https://github.com/osmcode/osm-area-tools/blob/master/src/oat_create_areas.cpp for instance, you'll see it appear in the output.

**Comment by woodpeck** [comment]
Sorry for the confusion. I changed the inner ring to wood and the outer to farmland, and sure enough, the inner ring is output, so the bug I thought I saw is a phantom. I still wonder why, since the `landuse=forest`/`natural=wood` filter existed in `osmium_area_test` even before the commit in question, the older builds *did* output the farmland though.
