### ISSUE TITLE
Build Error: no matching function for call

### ISSUE THREAD

**Issue by SunStormRain** [osmcode/libosmium#260]
I would like to compile the release v2.14.0 with Debian GNU/ Linux 9 but the building process (_make_) stops with: 

**[ 53%] Building CXX object test/CMakeFiles/io_test_pbf.dir/t/io/test_pbf.cpp.o**
In file included from ...libosmium/include/osmium/io/detail/pbf_input_format.hpp:38:0,
                 from ...libosmium/include/osmium/io/pbf_input.hpp:45,
                 from ...libosmium/test/t/io/test_pbf.cpp:5:
...libosmium/include/osmium/io/detail/pbf_decoder.hpp: In member function 'void osmium::io::detail::PBFPrimitiveBlockDecoder::decode_stringtable(const protozero::data_view&)':
...libosmium/include/osmium/io/detail/pbf_decoder.hpp:105:134: **error: no matching function for call to** 'protozero::pbf_message<osmium::io::detail::OSMFormat::StringTable>::next(osmium::io::detail::OSMFormat::StringTable, protozero::pbf_wire_type)'
                     while (pbf_string _[...]_

---------
Status/ Already Done:
- got the code via _git clone_
- release v2.13.1 compiles here nicely
- _cmake .._ does not show any missing libraries
- _make cppcheck_ does not show any vital issues
- changes settings in _ccmake .._ : everything OFF (which is possible to turn off)
- had a look in the code and could not find any obvious reasons (I'm not a c++ programmer)

**Comment by joto** [comment]
Looks a bit like you are missing the `protozero` library or have a version that's too old. Cmake should tell you that, though. Make sure you have version 1.5.1 or newer installed and only one version of it on your system.

**Comment by SunStormRain** [comment]
I had two protozero versions installed. The `cmake ..` from libosmium showed
`Found Protozero: /usr/include (found suitable version "1.5.1", minimum required is "1.5.1")`
when the error occured.

I removed protozero and used protozero v1.6.3 . Now libosmium compiles just fine.

Thanks for the fast response!
