### ISSUE TITLE
add_metadata list of attributes - no effect on history file output

### ISSUE THREAD

**Issue by SunStormRain** [osmcode/libosmium#261]
I would like to write osm history files with only version and timestamp information using libosmium release v2.14.0 (Debian GNU/ Linux 9). I used the following command separating the attributes with + like suggested in the release note:
`osmium cat file-history.osm -o file-history-VT.osm -f osm,add_metadata=version+timestamp --overwrite`

I expected version and timestamp data to be included but no uid, no user and no changeset data. The output file included all of them like I would have used `add_metadata=true`.

**Comment by joto** [comment]
I can't reproduce this. Are you sure you are calling the right `osmium` program? Try `osmium version`, it tells you which version of the osmium program and of libosmium it is.

**Comment by SunStormRain** [comment]
Yes, `osmium version` showed libosmium version 2.13.1. Right hint!
Thank you
