### ISSUE TITLE
Build broken on MinGW

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#262]
The build on MinGW has been broken for a while. See

https://ci.appveyor.com/project/Mapbox/libosmium/build/job/vjloy4jdwoai8dw1

@alex85k any ideas?

**Comment by alex85k** [comment]
Will try to check and help!

**Comment by alex85k** [comment]
The bug is in MSYS2 gdal package. It tries to to load "libjson-c-3.dll" but "libjson-c-4.dll" is present. Will try to fix there or create an issue. This bug will be eliminated automatically after msys update.

As a temporary workaround, the line with
```
copy C:\msys64\mingw64\bin\libjson-c-4.dll C:\msys64\mingw64\bin\libjson-c-3.dll
```
can be added to appveyor install section.

**Comment by joto** [comment]
The workaround worked. I keep this issue open, so we remember to remove it at some point.

**Comment by alex85k** [comment]
The bug https://github.com/Alexpux/MINGW-packages/issues/4106 is fixed, the gdal package updated to 2.3.1 by Alexpux. The workaround can be removed now.

**Comment by mlt** [comment]
Something is off with version comparison. Is it a naming /pacman issue?
```
:: Starting full system upgrade...
warning: mingw-w64-i686-json-c: local (0.13_20171207-2) is newer than mingw32 (0.13.1_20180305-1)
warning: mingw-w64-x86_64-json-c: local (0.13_20171207-2) is newer than mingw64 (0.13.1_20180305-1)
 there is nothing to do
```

**Comment by joto** [comment]
Seems this is broken again and the workaround didn't help.

**Comment by joto** [comment]
Works currently.
