### ISSUE TITLE
Getting clang-tidy not found after calling cmake

### ISSUE THREAD

**Issue by chtnha** [osmcode/libosmium#264]
@joto I am trying to build OSM animation for Bhutan https://github.com/osmcode/osmium-contrib/issues/9 and trying both at my personal mac and iMac (Mac Sierra 10.12.6) at my work place. 

I am getting `clang-tidy` not found message after building `libosmium` in iMac. I know that clang-tidy is missing https://github.com/mapbox/protozero#clang-tidy, but I don't know how to install it. Please let me know how to install it.

<img width="832" alt="screen shot 2018-07-25 at 6 09 28 pm" src="https://user-images.githubusercontent.com/6770741/43201862-58051ad6-9037-11e8-9559-6b9f1d5e15b5.png">

After running  `ctest` following `make`, I noticed 2 `ogr` modules failing:

<img width="316" alt="screen shot 2018-07-25 at 6 14 37 pm" src="https://user-images.githubusercontent.com/6770741/43202373-f52aa726-9038-11e8-982d-edb5aa4904e0.png">

Let me know how to resolve these, Thank you!

**Comment by joto** [comment]
You don't need clang-tidy. That is only needed for developers and everything will work fine without it. The `Bus error`s you are seing are unrelated to clang-tidy. I don't know where they come from but it looks to me like there is a problem with you GDAL/OGR libraries. Possibly you have several of them installed and linking to the wrong one or something like this.

**Comment by chtnha** [comment]
Solved this issue by pulling Ubuntu image in docker. Refer https://github.com/osmcode/osmium-contrib/issues/9#issuecomment-410245429
