### ISSUE TITLE
[feature] ensuring reading all nodes before reading any ways in an OSM file

### ISSUE THREAD

**Issue by kkdd** [osmcode/libosmium#276]
Hello,
I would like to read all nodes before reading any ways in an OSM file. Is it possible when using libosmium?

**Comment by joto** [comment]
In most OSM files, all nodes come first, then all ways and then all relations. So if you read such a file with libosmium you will get all nodes first, and then all ways. If the OSM file you have is not sorted that way, simply read it twice, only the nodes on the first go, and only ways on the second. You can do this most efficiently by telling the `Reader` which types to read like so:

```
osmium::io::Reader reader{filename, osmium::osm_entity_bits::node};
```

**Comment by kkdd** [comment]
Thank you for your suggestion. I will use your method.
And if I would like to confirm whether osm files are "sorted, I would check them by using the following program:

```console
$ ./check_sorted osm/japan-latest.osm.pbf
file: osm/japan-latest.osm.pbf
sorted
$ 
```

```check_sorted.cpp
#include <fstream>
#include <iostream>
#include <osmium/handler.hpp>
#include <osmium/visitor.hpp>
#include <osmium/io/any_input.hpp>
#include <osmium/index/map/sparse_mem_array.hpp>

class MainHandler: public osmium::handler::Handler {
	public:
	uint64_t nodes = 0;
	uint64_t ways = 0;
	uint64_t relations = 0;

	void node(osmium::Node &n) {
		if (ways > 0 || relations > 0) {
			std::cout << "not sorted" << "\n";
			exit(1); 
		}
		nodes++;
	}

	void way(osmium::Way &w) {
		if (relations > 0) {
			std::cout << "not sorted" << "\n";
			exit(1); 
		}
		ways++;
	}

	void relation(osmium::Relation &) {
		relations++;
	}
};

int main(int argc, char *argv[]) {
	if (argc != 2) {
		std::cerr << "Usage: " << argv[0] << " OSMFILE\n";
		exit(1);
	}
	std::string fileName = argv[1];
	std::cout << "file: " << fileName << "\n";
	std::ifstream ifs(fileName);
	if (!ifs.is_open()) {
		std::cerr << "error: no such file" << "\n";
		exit(1);
	}
	osmium::io::File infile(fileName);
	osmium::io::Reader reader(infile);
	MainHandler handler;
	osmium::apply(reader, handler);
	reader.close();
	std::cout << "sorted\n";
}
```

**Comment by joto** [comment]
[osmium fileinfo -e](https://docs.osmcode.org/osmium/latest/osmium-fileinfo.html) can tell you whether an OSM file is sorted, it will also check that IDs are sorted. But your program might also work.

**Comment by kkdd** [comment]
Thank you for information about osmium.
