### ISSUE TITLE
Error when building against proj 6.0.0

### ISSUE THREAD

**Issue by nextstopsun** [osmcode/libosmium#277]
I'm trying to build libosmium with latest proj library.
I'm getting a test error:
```
Scanning dependencies of target geom_test_factory_with_projection
[ 33%] Building CXX object test/CMakeFiles/thread_test_util.dir/t/thread/test_util.cpp.o
[ 33%] Building CXX object test/CMakeFiles/geom_test_factory_with_projection.dir/t/geom/test_factory_with_projection.cpp.o
[ 34%] Linking CXX executable util_test_misc
In file included from /usr/src/libosmium/include/osmium/geom/projection.hpp:50:0,
                 from /usr/src/libosmium/test/t/geom/test_factory_with_projection.cpp:4:
/usr/local/include/proj_api.h:37:2: error: #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
 #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
```

What needs to be done to build successfully? 
Any special configure keys?

**Comment by nextstopsun** [comment]
[This](https://github.com/OSGeo/proj.4/blob/6.0/src/proj_api.h#L37) where this error comes from.
I guess other headers should be used instead.

**Comment by Nakaner** [comment]
Well, you use Proj 6 which has [major changes](https://github.com/OSGeo/proj.4/releases/tag/6.0.0) to the API.

**Comment by joto** [comment]
As @Nakaner said, there seems to be major changes in version 6. It seems we could just set `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` before doing the include, but I'd rather use the new API correctly from the beginning. If course this would need some `#ifdef`s or so, so that it still works with the old library version. If somebody wants to figure this out and send a pull request, that'd be great.

**Comment by cyper85** [comment]
> 
> 
> As @Nakaner said, there seems to be major changes in version 6. It seems we could just set `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` before doing the include, but I'd rather use the new API correctly from the beginning. If course this would need some `#ifdef`s or so, so that it still works with the old library version. If somebody wants to figure this out and send a pull request, that'd be great.

This isn't the solution. [proj_api.h will be removed in proj v7](https://github.com/OSGeo/PROJ/issues/836). The macro is only a workaround for v6. The best solution is to disintegrate the old api.

**Comment by joto** [comment]
9fa01832 has a stopgap solution until we find a better one. The version 6 API is sufficiently different from the earlier API that our code can't be made to work with the new API efficiently and without changes. It will need some time to figure this out. Closing here.
