### ISSUE TITLE
Complex multipolygon relation takes forever to compute

### ISSUE THREAD

**Issue by lonvia** [osmcode/libosmium#278]
The rather complex [relation 9436485](https://www.openstreetmap.org/api/0.6/relation/9436485/1)(now deleted) cannot be assembled by the libosmium's multipolygon code. The algorithm seems to be stuck in `osmium::area::detail::BasicAssembler::find_candidates()`. I gave up after 2 hours.

**Comment by joto** [comment]
Places where rings touch are unusual for normal multipolygons and the algorithm in libosmium that assembles multipolygons does not handle them well. If there are too many touching points it becomes very slow. This is not a problem for almost all multipolygons. As I am writing this there are only three relations in the OSM database with more than 100 touching points, all of them rather weird boundaries in the US. The mentioned relation 9436485 had more than 300 of those points.

I have added a commit to libosmium to simply ignore areas with more than 100 touching points to keep the processing speed within reasonable bounds. This is not an ideal solution, of course. It would be better to find an algorithm that handles this case in a better way, but this will not happen quickly.

**Comment by joto** [comment]
Is in version 2.15.2.

**Comment by woodpeck** [comment]
For information, another relation that triggered this bug (on systems not yet running the fixed osmium library) was https://www.openstreetmap.org/relation/163124 in its version of 17 April, 2020.
