### ISSUE TITLE
Failure on bbox tag within relation/way

### ISSUE THREAD

**Issue by wiktorn** [osmcode/libosmium#279]
Overpass and Osmose may generate files which includes bbox tag within `way` or `relation`. In case of Overpass, this is done when `out bbox` is used. In case of Osmose, all files in http://download.openstreetmap.fr/replication are affected apart from whole planet diffs.

Example failure:
```bash
$ curl -o failing.osc.gz http://download.openstreetmap.fr/replication/europe/monaco/minute/003/435/438.osc.gz
$ ./osmium show ./failing.osc.gz
Unknown element in <way>: bbox
header
  multiple object versions: yes
  bounding boxes:
4  options:
    generator = OsmSax
    version = 0.6

=============================================


^C
$ ./osmium --version
osmium version 1.10.0 (v1.10.0-19-g01bd7de)
libosmium version 2.15.1
Copyright (C) 2013-2019  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
(needs ctrl+c to exit, what might be a separate bug). The problem is reported in first line: `Unknown element in <way>: bbox`

Older versions of libosmium do not show this error:
```bash
$ osmium --version
osmium version 1.7.1
libosmium version 2.13.1
Copyright (C) 2013-2017  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by joto** [comment]
Thanks for the report. Newer libosmium versions are stricter in what they accept in OSM XML files. I have now changed libosmium to ignore `<bbox>` or `<bounds>` subelements (the latter created by Overpass API) on `<way>` or `<relation>` elements. This allows you to at least read those files without error, but it doesn't give you access to the bbox data from libosmium.

We could store the bbox internally in libosmiums Way/Relation data structures, but this is a bigger change. I hesitate to do this until somebody actually needs this.

I can not reproduce your problem with `ctrl-c` needed. If you want to pursue this, please open a new issue and supply some information about your system.

**Comment by wiktorn** [comment]
Thank you very much for prompt response. It it fixed now.

As for the `ctrl-c` problem I guess that it might be related with the fact, that I was running these tests on FreeBSD so it may be some FreeBSD quirk.
