### ISSUE TITLE
Assertion m_iter' failed

### ISSUE THREAD

**Issue by nlehuby** [osmcode/libosmium#282]
I get the following error when trying to diff between two files with osmium-tool

```
osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f opl -c
osmium: /var/install/libosmium/include/osmium/io/input_iterator.hpp:124: osmium::io::InputIterator<TSource, TItem>::value_type& osmium::io::InputIterator<TSource, TItem>::operator*() const [with TSource = osmium::io::Reader; TItem = osmium::OSMObject; osmium::io::InputIterator<TSource, TItem>::reference = osmium::OSMObject&; osmium::io::InputIterator<TSource, TItem>::value_type = osmium::OSMObject]: Assertion m_iter' failed.
```

Any idea why ?

the two OSM pbf files have been created with `osmium tags-filter` + `osmium time-filter`

osmium version 1.7.1
libosmium version 2.13.1

**Comment by joto** [comment]
That's definitely a bug somewhere. Can you give me the two files? Without them there isn't enough information for me to track this down.

**Comment by nlehuby** [comment]
I've uploaded the two files here:
- https://transfer.sh/zITd2/result_2019-04-01.osm.pbf
- https://transfer.sh/CaaoM/result_2019-04-25.osm.pbf

They have been produced from an osh.pbf file from Geofabrik with the following process:
- `osmium tags-filter ile-de-france-internal.osh.pbf 'ref:FR:STIF'  -o out.osh.pbf`
- `osmium getid --id-osm-file out.osh.pbf --with-history ile-de-france-internal.osh.pbf -o filtered.osh.pbf`
- `osmium time-filter filtered.osh.pbf 2019-04-01T00:00:00Z -o result_2019-04-01.osm.pbf`
- `osmium time-filter filtered.osh.pbf 2019-04-25T00:00:00Z -o result_2019-04-25.osm.pbf`
- `osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f debug,color -c` >> this one crashes

**Comment by joto** [comment]
I just tested this with current osmium (1.10.0) and libosmium (2.15.1) and can not reproduce this. So I  guess this got fixed somewhere along the way. Please try with a current version.

**Comment by ImreSamu** [comment]
just documenting:   ..  in my setup:   it is working ..  no crash..

tested with 
* with your 2 results_2019_* files
```
$ osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f debug,color -c | wc -l
324010
```
* with the current  `ile-de-france-internal.osh.pbf`
```
$ osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f debug,color -c | wc -l
309665
$ md5sum ile-de-france-internal.osh.pbf
5000046f7a11e9e5ac47c9e3e362791c  ile-de-france-internal.osh.pbf
```
my environment:
```
$ osmium version
osmium version 1.10.0 (v1.10.0-42-g7341b94)
libosmium version 2.15.1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

```

**Comment by ImreSamu** [comment]
just documenting:  
* problem replicated on `ubuntu:18.04` - with  `osmium-tool` package ( osmium version 1.7.1 libosmium version 2.13.1 )
* working:  `ubuntu:18.10`  ( osmium version 1.9.1   libosmium version 2.14.2 )
* working:  `ubuntu:19.04` ( osmium version 1.10.0 libosmium version 2.15.0 )

`docker run -it --rm ubuntu:18.04 bash`

```
apt-get update && apt-get install -y wget osmium-tool
wget https://transfer.sh/zITd2/result_2019-04-01.osm.pbf
wget https://transfer.sh/CaaoM/result_2019-04-25.osm.pbf
osmium version
osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f debug,color -c
```

```
root@0dac3daefbca:/# osmium version
osmium version 1.7.1
libosmium version 2.13.1
Copyright (C) 2013-2017  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
root@0dac3daefbca:/# osmium diff result_2019-04-01.osm.pbf result_2019-04-25.osm.pbf -f debug,color -c
osmium: /usr/include/osmium/io/input_iterator.hpp:124: osmium::io::InputIterator<TSource, TItem>::value_type& osmium::io::InputIterator<TSource, TItem>::operator*() const [with TSource = osmium::io::Reader; TItem = osmium::OSMObject; osmium::io::InputIterator<TSource, TItem>::reference = osmium::OSMObject&; osmium::io::InputIterator<TSource, TItem>::value_type = osmium::OSMObject]: Assertion `m_iter' failed.
Aborted (core dumped)
root@0dac3daefbca:/# 
```

**Comment by nlehuby** [comment]
the diff is ok with the version packaged with ubuntu 19.04, but I can't make any tags-filter with that version, I get another assertion failed :(

`docker run -it -w /wkd -v $(pwd)/wkd:/wkd osmium_1904 osmium --version`
```osmium version 1.10.0
libosmium version 2.15.0
Copyright (C) 2013-2018  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
`docker run -it -w /wkd -v $(pwd)/wkd:/wkd osmium_1904 osmium tags-filter data.osh.pbf highway=bus_stop -o out.osh.pbf`

```osmium: /usr/include/osmium/osm/node_ref_list.hpp:152: bool osmium::NodeRefList::is_closed() const: Assertion `!empty()' failed.```
```

**Comment by joto** [comment]
1. Please open new issues for new problems.
2. I can't reproduce this until I know what `data.osh.pbf` is.
3. From your use of a `.osh.pbf` file I can only assume that this is a history file. Quoting the tags-filter man page: "The command will only work correctly on history files if the --omit-referenced/-R option is used."  An assertion failure is still a bug that should be found and fixed, but your command line will not work even of we do.
