### ISSUE TITLE
Assertion !empty()' failed

### ISSUE THREAD

**Issue by nlehuby** [osmcode/libosmium#283]
with this [data file](https://transfer.sh/JAHwp/data.osh.pbf) for instance
`docker run -it -w /wkd -v $(pwd)/wkd:/wkd osmium_1904 osmium tags-filter data.osh.pbf tourism=museum -o out.osh.pbf -R`
returns
```
osmium: /usr/include/osmium/osm/node_ref_list.hpp:152: bool 

osmium::NodeRefList::is_closed() const: Assertion !empty()' failed.
```

`docker run -it -w /wkd -v $(pwd)/wkd:/wkd osmium_1904 osmium --version`
```
osmium version 1.10.0
libosmium version 2.15.0
```

**Comment by joto** [comment]
Works fine with current libosmium/osmium-tool.
