### ISSUE TITLE
Doubts about throwing exceptions in XML parser

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#287]
I ported some of your XML input parsing logic from expat to libxml (also C based XML SAX Parser) and now experienced some crashes on ARMv7 / Raspian only. This may sound a bit odd at first, but made me think about exception handling in your code as well:

In xml_input_format.hpp, amonst other calls, start and end element functions are set:
   
```C++
 XML_SetElementHandler(m_parser, start_element_wrapper, end_element_wrapper);
```

They both point to the respective static methods in ExpatXMLParser:

```C++
                class ExpatXMLParser {

                    XML_Parser m_parser;

                    static void XMLCALL start_element_wrapper(void* data, const XML_Char* element, const XML_Char** attrs) {
                        static_cast<XMLParser*>(data)->start_element(element, attrs);
                    }

                    static void XMLCALL end_element_wrapper(void* data, const XML_Char* element) {
                        static_cast<XMLParser*>(data)->end_element(element);
                    }
```

When a new element start or ends, we would call one of the following two methods:
As an example, let's take a look at: 
```
     void start_element(const XML_Char* element, const XML_Char** attrs) {

     case context::node:
           if (!std::strcmp(element, "tag")) {
[...]
          } else {
         throw xml_error{std::string{"Unknown element in <node>: "} + element};   <<<<<< throws exception
        }
      break;
```

Here we throw an xml_error exception. However, at this time, we still have expat (as C library) in our callstack, and we propagate this exception right through the Expat library back to the caller (!).

Let's take a look how libxml++ (a C++ wrapper for libxml) implements exception handling and passing from C++ -> C --> C++:

https://github.com/GNOME/libxmlplusplus/blob/master/libxml%2B%2B/parsers/saxparser.cc#L449-L471 & https://github.com/GNOME/libxmlplusplus/blob/libxml++-3.0/libxml++/parsers/parser.cc#L321-L352

The approach is different in a way, that the exception is stored in the XML parser context while still in C land,  XML parsing aborted, and only once the C code XML parsing has finished, the stored exception will be thrown again in C++ land.

(that's similar to: https://stackoverflow.com/questions/11118781/expat-exception-handling/22080719#22080719)

Does this make sense to you? Did I maybe miss something?

**Comment by joto** [comment]
Looks like you are right. Throwing an exception through C code isn't guaranteed to work. So far it has always worked for me, but it is clearly something that might break, so I should fix that.

Incidentally, why are you switching from expat to libxml? Waaay back I tried both and expat had better performance for me so I settled on that.

**Comment by mmd-osm** [comment]
> Incidentally, why are you switching from expat to libxml? 

The existing codebase already used libxml in other places, and having two different XML parser libraries felt like a bit of an overkill, so I adopted the code to work on libxml. I would have probably used expat as well on a new project.
