### ISSUE TITLE
Failing to compile libosmium in my project

### ISSUE THREAD

**Issue by Uranus45** [osmcode/libosmium#290]
Hi, I'm trying to use osmium in my own project. I installed all project dependencies, added `FindOsmium.cmake` and `FindProtozero.cmake` and configured `CMakeLists.txt` like this 
```
list(APPEND CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")
find_package(Osmium REQUIRED COMPONENTS pbf)
include_directories(SYSTEM ${OSMIUM_INCLUDE_DIRS})
```

But every time I try to compile the code using `make` I get the folowing error: `#include <osmium/io/pbf_input.hpp> fatal error: 'osmium/io/pbf_input.hpp' file not found`. I configured all variables using `ccmake ..` and `cmake ..` executes succesfully. Can you please point me in the right direction of solving this issue?

**Comment by Nakaner** [comment]
How is your C++ compiler called? Please run `make VERBOSE=1`.

What are the include paths determined by CMake? Please run `ccmake ..`, press T and look for the variables starting with OSMIUM and PROTOZERO.

If you need a example project using Libosmium, have a look at https://github.com/geofabrik/osmi_simple_views

**Comment by Uranus45** [comment]
I removed dependencies from project source and installed them via homebrew (and some from their source) and now I'm getting a different error when using `#include <osmium/io/pbf_input.hpp>`:

Undefined symbols for architecture x86_64:
```
  "_uncompress", referenced from:
      osmium::io::detail::zlib_uncompress_string(char const*, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in main.cpp.o
     (maybe you meant: osmium::io::detail::zlib_uncompress_string(char const*, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&))
  "_zError", referenced from:
      osmium::io::detail::zlib_uncompress_string(char const*, unsigned long, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Under `CMAKE_CXX_COMPILER` I have  `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ `.

Since this looks like a problem with zlib I tried to compile a sample project with only `#include <zlib.h>` and it compiles successfully. Also I installed zlib from its source.

**Comment by Uranus45** [comment]
Adding this in CMakeLists.txt solved my issue, hope this helps if someone occurs a similar issue.
`target_link_libraries(MyProject ${OSMIUM_LIBRARIES})`
