### ISSUE TITLE
area.is_multipolygon() might not work as expected

### ISSUE THREAD

**Issue by ln-12** [osmcode/libosmium#293]
Hey guys, first of all I want to thank you for your awesome work on this library!

I've been using it for a while now and encountered a problem. In the osmium_area_test example I want to add a simple check if an area is a multipolygon. For testing, I used [this relation](https://www.openstreetmap.org/relation/3091999). When checking with `area.is_multipolygon()` at [this position](https://github.com/osmcode/libosmium/blob/master/examples/osmium_area_test.cpp#L77), it returns false although there is clearly one outer and one inner ring. 

In the [OSM wiki](https://wiki.openstreetmap.org/wiki/Relation:multipolygon) the definition of multipolygon is:

> However, this model only works for areas the outline of which consists of one single way, and which do not have holes. Any area that is more complex than that (e.g., because its outline consists of several ways joined together, or because the area consists of multiple disjunct parts, or has holes) requires a multipolygon relation. 

Am I understanding something wrong or is there a bug? Thanks for your help!

**Comment by joto** [comment]
The definition of "multipolygon" is somewhat confusing. In the OSM world we say something is a multipolygon when it is mapped as a "multipolygon relation". But this is not what this function is about.

In the usual (non-OSM) definition a "polygon" has exactly one outer ring and zero or more inner rings. a "multipolygon" has more than one outer ring (and each outer ring can have zero or more inner rings). And this is what the `area.is_multipolygon()` tells you. The docs for it say: "Check whether this area is a multipolygon, ie. whether it has more than one outer ring?".

If you want to check whether an area was created from a way or a (multipolygon) relation, you can use the `from_way()` function.

**Comment by ln-12** [comment]
Thanks for your fast and detailed explanation, that helps a lot!
