### ISSUE TITLE
cmake fails.

### ISSUE THREAD

**Issue by gorishaa9** [osmcode/libosmium#296]
Hi,

I have installed all the dependencies needed by `libosmium`. However, the `cmake ..` issues a warning saying `Could not find Protozero: Found unsuitable version -- 1.6.1, required >= 1.6.3`. I am running it on Ubuntu Bionic Beaver (18.04) and `libprotozero-dev` installs 1.6.1. I also tried to manually build and install it, but the same issue again.
Also, the documentation says that `protozero` is not needed by the latest version of libosmium. The `cmake` still shows the problem. What am I missing?

Please let me know. Thanks.

**Comment by joto** [comment]
You still need protozero. I don't know where you read that you don't need it, but that was probably a misunderstanding. If you manually installed a current protozero version and it didn't work than libosmium probably didn't find it. First, make sure you deinstalled the Ubuntu one, having multiple versions installed if often a problem. Then tell libosmium where you installed protozero, i recommend the `ccmake` program to do that, but see the cmake docs on how to change settings in cmake.

**Comment by gorishaa9** [comment]
Thanks for you reply. I simply removed all the `build` files and did the `build` again. It worked, passed all the tests.
On the other note, I misunderstood about `protozero`. Thanks for clarifying.
