### ISSUE TITLE
Distance conversion.

### ISSUE THREAD

**Issue by gorishaa9** [osmcode/libosmium#299]
The class `osmium::Location` has members `x` and `y` of type `int32_t`. I want to interpret it in metres. Since `int32_t` type can represent `2^32` values, the value of 1 unit of `int32_t` will convert to:
`2*R/2^32`. Is this correct, given `(0,0)` is the origin and `R` is the mean radius of the earth in metres?

Please let me know. Thanks.

**Comment by joto** [comment]
No. The x and y values are internal fixed point representations of the lat/lon. You should not normally use them. Use lat() and lon() and project/convert that. How to do that is outside the scope of Osmium.
