### ISSUE TITLE
Regarding conversion of Coordinates from lonlat_to_mercator.

### ISSUE THREAD

**Issue by gorishaa9** [osmcode/libosmium#300]
Hi,

I want the unit of the coordinates of the points in metres. For this reason, I am using `lonlat_to_mercator()` to obtain the coordinates in EPSG:3857. However, now I want a buffer around a way (linestring). For this, I am converting these osmium web mercator coordinates to `geos::geom::Coordinate` to create `geos::geom::Linestring` object to be able to use `buffer()` to obtain the buffer around this linestring object.
For this, as the `geos` requires to define a `PrecisionModel` and create an instance of `GeometryFactory`, I am doing as follows:
`PrecisionModel* pm = new PrecisionModel(1000);`
`auto global_factory = GeometryFactory::create(pm, 3857)`

Transforming the coordinates in web mercator projection `osmium::geom::Coordinates c`, I do the following:
`Coordinate cm{pm->makePrecise(c.x), pm->makePrecise(c.y)}`

When I print the coordinates `cm`, the values are changed. For example, if the coordinates `c` is:
`-1.26426e+07    7.028e+06`
the coordinates `cm` are as follows:
`7.028e+06    0`

It is always the case that after applying the precision model, the x-coordinate value is the y-coordinate of the original coordinates and the y-coordinate after applying the precision model is always 0. 

Also, I need the coordinates in metres so that I can provide the width of the buffer in metres to be formed around the linestring. I tried hard but couldn't understand where I am going wrong. 

Any help will be greatly appreciated. Thanks.

**Comment by joto** [comment]
https://osmcode.org/libosmium/manual.html#creating-geometries has a section on how to create GEOS geometries. Instead of 4326 use 3857 and you will get Mercator coordinates in your GEOS geometries. Everything else is outside the scope of what I can answer here.

**Comment by gorishaa9** [comment]
Okay, thanks.
