### ISSUE TITLE
No element inside <member> allowed

### ISSUE THREAD

**Issue by KuDeSnik33ra** [osmcode/libosmium#305]
Hello! I am trying to load osm file to osmium and get exception = "No element inside `<member>` allowed". OSM file is downloaded from OSM server. What is wrong here? As I understand it is about such part of osm file:
```
<relation id="359962">
		<member type="way" ref="177626860" role="main_stream">
			<nd lat="56.5163919" lon="39.5103687"/>
		</member>
</relation>

**Comment by pnorman** [comment]
That is not valid OSM XML. A relation contains an ordered list of member elements as well as unordered tag elements. The member elements do not have any children.

**Comment by KuDeSnik33ra** [comment]
Such files are produced by https://overpass.kumi.systems/api/. Overpass request is:
```(
node({{bbox}})[!place];
rel(bn)[!route]->.x;
way({{bbox}})[!boundary];
node(w)[!route]->.x;
rel(bw)[!route];
);
(._;>;);
out geom;

**Comment by joto** [comment]
@pnorman is right, this is not the normal OSM format. Overpass has extended the format in its own way and Osmium doesn't understand that extended format.

**Comment by KuDeSnik33ra** [comment]
Is it possible to skip nd children of member without exception? They are duplicated.

**Comment by KuDeSnik33ra** [comment]
```
<way id="177626860">
		<nd ref="3328681016" lat="56.5163919" lon="39.5103687"/>
		<nd ref="3328681015" lat="56.5161577" lon="39.5101207"/>
		<nd ref="3328681014" lat="56.5158978" lon="39.5095226"/>
</way>
<relation id="359962">
		<member type="way" ref="177626860" role="main_stream">
			<nd lat="56.5163919" lon="39.5103687"/>
			<nd lat="56.5161577" lon="39.5101207"/>
			<nd lat="56.5158978" lon="39.5095226"/>
		</member>
</relation>

**Comment by KuDeSnik33ra** [comment]
I swapped line 590 in xml_input_format.hpp file to fix this:
before:
`throw xml_error{"No element inside <member> allowed"};`
after
```
m_context_stack.push_back(context::other);
break;
```

**Comment by joto** [comment]
I don't like to do this kind of thing, because we are essentially guessing what parts of the data can still be read and what aren't and how the data is to be interpreted. I'd rather bring an error and tell the user something is wrong than silently doing something which might be right or not.

I think this is really something to be fixed on the Overpass side. I can understand that the Overpass wants to put additional information in its output files which can be useful sometimes, but it should also allow you to get a standard OSM file.

**Comment by KuDeSnik33ra** [comment]
It looks like a problem of authority. I don't know - who is creator and owner of OSM file standart, I am just trying to get data from OSM server and load it. My IMHO - skip some data is not a problem.

**Comment by joto** [comment]
Try using `out;` instead of `out geom;`. That should generate the standard OSM format. I am not an Overpass expert, so if you have any more problems I suggest you ask the Overpass people how to solve your problem, they might have a better idea.

**Comment by mmd-osm** [comment]
Combining (._;>;); and out geom; doesn’t really make sense here anyway as it’s returning duplicate data.

As @joto wrote replace out geom; by out; or maybe out meta; depending on your use case. 

You didn’t describe what you’re trying to do in the first place. For things like converting Osm to geojson there are existing libs handling out geom output.

**Comment by KuDeSnik33ra** [comment]
I am trying ti read osm files for creating railroads in 3d engine. OSM files can be downloaded in diffrent ways - in my case it has such duplicate data - what is the problem to skip it? Why anybody can need to stop reading file in such case? This file was not created by 3rdparty - it was created by opensteetmap.  Osmium does not support it. Is this OK?

**Comment by joto** [comment]
> This file was not created by 3rdparty - it was created by opensteetmap. 

The file was created by Overpass, not "openstreetmap". Overpass is one program among many that has something to do with OSM, so is Osmium. Overpass does its own thing here on top of what most OSM programs support. Osmium doesn't support the extensions of Overpass. We have explained what you can do to use Overpass in a compatible way. This is getting off-topic here. Closing.
