### ISSUE TITLE
Add install instructions for vcpkg 

### ISSUE THREAD

**Issue by kelteseth** [osmcode/libosmium#306]
Hi,
Thanks for this amazing software! I  compiled all dependencies successful and fully automatic via vcpkg on my Windows machine. 

`vcpkg.exe install protozero utfcpp expat zlib boost-iterator bzip2  boost-variant geos gdal`

Need to set the toolchain file for cmake (in my QtCreator):

``` cmake
CMAKE_TOOLCHAIN_FILE:STRING=%{CurrentProject:Path}/External/vcpkg/scripts/buildsystems/vcpkg.cmake
VCPKG_TARGET_TRIPLET:STRING=x86-windows
```
Maybe we could add libosmium to vcpkg? I guess this would be pretty easy because we already can install all dependencies via vcpkg.

**Comment by joto** [comment]
Packaging is outside the scope of the project itself, but I encourage everybody who knows anything about vcpkg (or, for that matter, any other packaging system) to set up and maintain packages.

**Comment by kelteseth** [comment]
Some just did the port for vcpkg -> https://github.com/microsoft/vcpkg/tree/a0c5fc8e6e67c7a0ccf9df5e708423b9137a30d8/ports/libosmium

Can we fix the build instruction for all platforms to 

- `vcpkg install libosmium`

Should now be by far the easiest way to install :)
