### ISSUE TITLE
Support for reading OSM data in JOSM format

### ISSUE THREAD

**Issue by cyang-kth** [osmcode/libosmium#307]
According to the format specified on https://wiki.openstreetmap.org/wiki/OSM_file_formats
it would be great if the library can support reading OSM file in JOSM format.

**Comment by cyang-kth** [comment]
It seems that when we read a file generated by osmconvert. The geometry of some nodes cannot be found. 
 
```
terminating with uncaught exception of type osmium::not_found: location for one or more nodes not found in node location index
```

**Comment by joto** [comment]
a) Don't create issues with several unrelated issue in them. There is no way I can sensibly keep track of anything if things are mixed up, so I will just closed them.
b) Please describe exactly what you are trying to achieve. Otherwise we can't help you.
