### ISSUE TITLE
Regarding writing the data from the buffer in osm file.

### ISSUE THREAD

**Issue by gorishaa9** [osmcode/libosmium#308]
Hi, I am trying to modify the road segments in the database and write it to an osm file. I have pretty much used the same code as in the libosmium documentation and examples in the github to write the data from the buffer to an output file.

I have the road segments, with the noderefs. I create a way from these noderefs as follows : 
```
const int buffer_size = 1024000;
Buffer buffer{buffer_size, Buffer::auto_grow::yes};
osmium::io::File output_file{outfile_name};
Writer writer{output_file, osmium::io::overwrite::allow};

void build_way(SVal missing_seg){
        WayBuilder way_builder{buffer};
        osmium::Way& obj = way_builder.object();
        obj.set_id(new_id++);
        obj.set_version(1);
        way_builder.add_user("foo");
        {
            WayNodeListBuilder wnl_builder{buffer, &way_builder};
            for(auto& c : missing_seg->get_intermediate_nodes()){
                wnl_builder.add_node_ref(osmium::NodeRef(new_id++, osmium::Location(c.x, c.y)));
                cout << c.x << "\t" << c.y << "\n";
            }
        }
        add_tags(&way_builder, missing_seg->tags());
        buffer.add_item(obj);

build_way(seg);
buffer.commit();
cout << buffer.data();
writer(std::move(buffer));
writer.close();
```

The statement `buffer.commit()` does return some non-zero bytes but when I try to print `buffer.data()`, it prints nothing. Also, the `buffer` is a global variable. Since the `buffer.data()` is empty `unsigned char*`, the result file has no data. I am finding it difficult to figure out why this is so.

Any help will be greatly appreciated. Thanks.

**Comment by joto** [comment]
There are several problems with your code. First, `cout << buffer.data();` doesn't make any sense. The data in the buffer is binary data, you can't output it this way and expect something useful. Then there is the `buffer.add_item(obj);` line. The `WayBuilder way_builder{buffer};` already adds the way you are building to the buffer, you don't need that `add_item()` line here. The rest looks reasonably okay, but I can't test it of course. I don't know what you mean with "The statement buffer.commit() does return some non-zero bytes", `buffer.commit()` returns the number of bytes that were committed before, in this case it should return 0.

**Comment by gorishaa9** [comment]
I have tested the code without the `buffer.add_item()` and `buffer.commit()` gives 0 bytes but `buffer.committed()` gives non-zero bytes. I still get an empty output osm file.

**Comment by joto** [comment]
I can't help you more than this without some actual compilable code.

**Comment by gorishaa9** [comment]
I tried something. I ran the code in the libosmium github examples : https://github.com/osmcode/libosmium/blob/master/examples/osmium_create_pois.cpp

I could see the newly created point of interests. To this code, I added this code in the main 

```
{
        osmium::builder::WayBuilder way_builder{buffer};
        way_builder.object().set_id(3);
        way_builder.object().set_version(1);
        way_builder.add_user("foo");
        {
            osmium::builder::WayNodeListBuilder wnl_builder{buffer, &way_builder};
            wnl_builder.add_node_ref(osmium::NodeRef (1, osmium::Location{1.22, 3.45}));
            wnl_builder.add_node_ref(osmium::NodeRef (2, osmium::Location{1.24, 3.47}));
        }
}
buffer.commit();
```

I couldn't see the created way. I am viewing the result file in JOSM. I could see the POIs. However, in the example code, the POIs were created with the ID -1 and -2 respectively. But when I view the file in JOSM, it shows ID "0" for either of the POIs. And I can see nothing for the way. Is there something that I am missing? Please let me know. Thanks.

**Comment by joto** [comment]
I can't help you unless you I have the complete code you are using.

**Comment by gorishaa9** [comment]
[test_write.zip](https://github.com/osmcode/libosmium/files/4859888/test_write.zip)

The above file contains the code. Please take a look. Thanks.

**Comment by joto** [comment]
When I try your code it does exactly what I would expect it to do. It creates this file:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="libosmium/2.15.6">
  <way id="3" version="1" user="foo">
    <nd ref="4"/>
    <nd ref="5"/>
  </way>
</osm>
```

I think the confusion might be because of code like `wnl_builder.add_node_ref(osmium::NodeRef (1, osmium::Location{1.22, 3.45}))`. This will only include the way nodes (the `<nd ref="4"/>`), not the node entry itself. You have to create the nodes yourself before you create the way using those nodes. There is some commented out code already in test_write.cpp that essentially does this.

**Comment by gorishaa9** [comment]
Hi, thank you for your time and help. I see the problem and will do as directed. Thanks.
