### ISSUE TITLE
Question on osmium::io::detail status

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#310]
osmium::io::detail is described as "Namespace for osmium internal use" and not listed on https://docs.osmcode.org/libosmium/latest/files.html. I'm not quite sure what the implications for users outside of libosmium are. As an example, osmdbt uses the following two functions:

```
    osmium::io::detail::reliable_write(fd, output.data(), output.size());
    osmium::io::detail::reliable_close(fd);
```

I found this hint on the https://osmcode.org/libosmium/manual.html website, saying "Do not directly use anything in any sub-namespace called detail. Those classes and functions are for internal use only.". Does this also apply to osmium::io::detail? Do you see any disadvantages to use those functions outside of libosmium?

Thanks for a short feedback!

**Comment by joto** [comment]
Those functions are internal and I reserve the right to change them at any time and nobody gets to complain. I use them in my own software sometimes, because I can.

**Comment by mmd-osm** [comment]
Thanks for your quick reply, I think this answered my question!
