### ISSUE TITLE
uapi/linux/stddef.h error on red hat linux 7.4

### ISSUE THREAD

**Issue by jaigsingla** [osmcode/libosmium#313]
Hi ,

configuration is built successfully  but while make I am getting uapi/linux/stddef.h error on red hat linux 7.4 with gcc and g++ 4.5.8 ??

**Comment by joto** [comment]
Red Hat Linux 7.4 is more than three years old. And libosmium needs at least GCC 4.8 as it says in the README. Update your system.

**Comment by jaigsingla** [comment]
oh sorry . 
gcc and g++ version is 4.8.5 20150623

**Comment by joto** [comment]
Still, a pretty old system and not enough information to go on. Sorry, but you are on your own there.

**Comment by jaigsingla** [comment]
Hi,
Updated linux 7.4 to 7.9 
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

Red Hat Enterprise Linux Workstation release 7.9 (Maipo)  and updated gcc 4.8.5 to gcc 7.5 

still no luck. Pls let me know what more details you need ??

Error trace 

[  1%] Building CXX object test/CMakeFiles/testlib.dir/test_main.cpp.o
In file included from /usr/include/wchar.h:51:0,
                 from /usr/include/c++/4.8.2/cwchar:44,
                 from /usr/include/c++/4.8.2/bits/postypes.h:40,
                 from /usr/include/c++/4.8.2/iosfwd:40,
                 from /usr/include/c++/4.8.2/ios:38,
                 from /usr/include/c++/4.8.2/istream:38,
                 from /usr/include/c++/4.8.2/sstream:38,
                 from /home/deep/osmium/libosmium-2.15.6/test/catch/catch.hpp:384,
                 from /home/deep/osmium/libosmium-2.15.6/test/test_main.cpp:2:
/usr/src/kernels/3.10.0-693.el7.x86_64/include/linux/stddef.h:4:31: fatal error: uapi/linux/stddef.h: No such file or directory
 #include <uapi/linux/stddef.h>
