### ISSUE TITLE
Can't build libosmium with LZ4 support on Windows using VS2017

### ISSUE THREAD

**Issue by sphoto** [osmcode/libosmium#317]
Since Windows does not come with `pkg-config` installed (at least when using Visual Studio), cmake stops with
`Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)`

It would be nice to have a cross-platform solution instead of pkg-config. Thank you!

**Comment by joto** [comment]
I have removed the check with pkg-config and instead use the "old-fashioned" way with `find_library()`. You might have to set the `LZ4_INCLUDE_DIR` and `LZ4_LIBRARY` variables manually.

**Comment by sphoto** [comment]
Works perfectly, thank you!
