### ISSUE TITLE
Test failures for tags_test_tag_list

### ISSUE THREAD

**Issue by tomhughes** [osmcode/libosmium#319]
I'm seeing test failures in `tags_test_tag_list`:

```
tags_test_tag_list is a Catch v1.12.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
create tag list
-------------------------------------------------------------------------------
/builddir/build/BUILD/libosmium-2.16.0/libosmium/test/t/tags/test_tag_list.cpp:15
...............................................................................

/builddir/build/BUILD/libosmium-2.16.0/libosmium/test/t/tags/test_tag_list.cpp:176: FAILED:
  REQUIRE( std::string("highway") == it->key() )
with expansion:
  "highway" == "name"
```

I've seen this intermittently before but couldn't figure out the cause - the tags seem to be in the wrong order but they're added from an ordered map to ought to be ordered. So far in 2.16.0 it has happened three times in a row.

**Comment by tomhughes** [comment]
Ah, but it's a map with `const char *`keys so it is ordering by address not by string!

**Comment by joto** [comment]
Wow. Thanks for finding and diagnosing this. That code has been in there for 4 years and I have never seen it fail in that time.
