### ISSUE TITLE
How do I create a filter rule with a logical AND?

### ISSUE THREAD

**Issue by Yaseen787** [osmcode/libosmium#323]
I'm using the Osmium C++ library to extract coastline data (for a university project) from OSM data. I first tried using a filter as follows:

```
osmium::TagsFilter filter{false};
filter.add_rule(true, osmium::TagMatcher{"natural", "coastline"});
```

but it seems that this only gives coastlines of small islands. I'm guessing this is because I need to somehow include coastlines formed by multipolygon relations. I've tried changing the rule to be:

```
osmium::TagsFilter filter{false};
filter.add_rule(true, osmium::TagMatcher{"natural", "coastline"});
filter.add_rule(true, osmium::TagMatcher{"type", "multipolygon"});
```

but this seems to add the rules in an OR fashion as opposed to an AND one, and so I end up with large amounts of irrelevant data that I don't need. Is there a way to filter only data that has ("natural", "coastline") AND ("type", "multipolygon") key-value pairs?

**Comment by joto** [comment]
The coastline in OSM is only defined by ways, not by relations. See https://wiki.openstreetmap.org/wiki/Tag:natural%3Dcoastline . So your first filter is fine. But you will get the coastline in separate "pieces". Assembling the coastline can be a bit tricky, so there are specialized tools for getting the coastline out of OSM data: https://osmcode.org/osmcoastline/ and you can download the result of that tool from https://osmdata.openstreetmap.de/ . 

When using the TagsFilter with several matchers you should not think in terms of AND and OR! The rules are matched in order from first to last and you can build any combination you like. There are several ways to do this, but for a simple AND-match you can simply invert all the rules. So something like this:

```
osmium::TagsFilter filter{true}; // return true from filter if nothing matches
filter.add_rule(false, osmium::TagMatcher{"natural", "coastline", true}); // return false if natural=coastline does not match
filter.add_rule(false, osmium::TagMatcher{"type", "multipolygon", true}); // return false if type=multipolygon does not match
```

**Comment by Yaseen787** [comment]
Unfortunately, I need to implement the coastline extraction functionality for the project. 

I tried your solution but it still results in really large data outputs that I'm sure involved information beyond coastlines. Currently, I'm working on extracting coastlines by extracting either ways that form a closed-loop, or through ways that are a member of some relation and have the tag ("natural", "coastline"). Currently, this is what I have for the relation callback:

```
void relation(const osmium::Relation& relation) {

        if (relation.tags().has_tag("type", "multipolygon")) {

            const osmium::RelationMemberList& rml = relation.members();

            for (const osmium::RelationMember& rm : rml) {

                if (rm.get_object().tags().has_tag("natural", "coastline")) {
                   // extract the nodes in those ways somehow
                }

            }
        }
    }
```

But this seems to cause some runtime error from the line:

`rm.get_object().tags().has_tag("natural", "coastline")`

**Comment by pnorman** [comment]
> I tried your solution but it still results in really large data outputs that I'm sure involved information beyond coastlines. Currently, I'm working on extracting coastlines by extracting either ways that form a closed-loop, or through ways that are a member of some relation and have the tag ("natural", "coastline"). Currently, this is what I have for the relation callback:

This doesn't answer your question on the runtime error, but you haven't provided the error, but...

Coastline ways don't need to be a closed loop and don't need to be part of a relation. e.g. https://www.openstreetmap.org/way/22393947 is properly mapped, not closed, and not part of a relation.

**Comment by Yaseen787** [comment]
After some research, it seems that I had to use a so called location manager, and things seem to work without runtime errors.

Well then, how do you suggest I go about to get all closed coastlines then? From what you say, it seems that there is nothing really that I could do.

**Comment by joto** [comment]
I have already provided you with a link to a program that does the coastline assembly. If you don't want to use that program that's fine. I suggest studying it though, that should give you an idea how you can handle this yourself. Anyway, this has moved beyond the original question which was answered, so I am closing this here.
