### ISSUE TITLE
Undefined behaviour on 32-bit due to m_file_size declared as std::size_t

### ISSUE THREAD

**Issue by mloskot** [osmcode/libosmium#324]
The switch to `BZ2_bzWriteClose64` in https://github.com/osmcode/libosmium/commit/54894fdbb2d70e11a5e22cf0298bc12cdec95e59 seems to cause undefined behaviour on 32-bit architectures or any where `std::size_t` is defined as 32-bit type, that is due to left-shift by 32 bits in 

https://github.com/osmcode/libosmium/blob/54894fdbb2d70e11a5e22cf0298bc12cdec95e59/include/osmium/io/bzip2_compression.hpp#L233

It seems the switch to `BZ2_bzWriteClose64` should be completed with re-declaring `m_file_size` as `std::uint64_t` instead of `std::size_t`.

------

Applies to current [v2.16.0](https://github.com/osmcode/libosmium/tree/v2.16.0) and current [master](https://github.com/osmcode/libosmium/tree/072612ab976b1356de3993eea2f9c56d8232c863).

------

By the way, that undefined behaviour may lead to [seemingly correct result](https://codeyarns.com/tech/2004-12-20-c-shift-operator-mayhem.html) or [shift by 32-bits is the same as a shift by 0-bits](http://blog.llvm.org/2011/05/what-every-c-programmer-should-know.html) but [it should not be relied on](https://www.viva64.com/en/w/v3134/).

**Comment by joto** [comment]
Good catch! We have to remove the UB of course. I don't want to switch to `unit64_t` though, because that would mean there would be lots of changes needed elsewhere, including in client code. Reading large files on 32 bit systems will probably not work anyway.

**Comment by joto** [comment]
Fixed in 1705adb8afb46baa8216fe55312b2ede2931b2e4.

**Comment by mloskot** [comment]
> The fix is not perfect, because it will not report the correct result on 32bit systems, but I can live with that.

I considered similar patch too, but I was not sure if you will accept it :-) thus I suggested the type change. I can live with the fix too. Thanks!
