### ISSUE TITLE
opl parsing issue

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#328]
I'm reporting an opl format parsing issue along with a minimum test case to reproduce it on the latest osmium-tool. The issue should be in libosmium, though.

```shell
echo -n "w1 T%%=" | osmium cat - -F opl -f xml
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
Segmentation fault (core dumped)
```

**Comment by mmd-osm** [comment]
Thanks for the quick fix, result looks good here. I wasn't even aware that "%%" currently has undefined behavior, which is now explained in more detail in https://github.com/osmcode/osmcode.github.io/commit/8ef695e51be2916ca9b66b061ca3beef0835bc15

**Comment by joto** [comment]
I wasn't aware of it either. :-) But I thought I define it as undefined in the docs now so that nobody depends on some behaviour which all the old software will not deliver. Thanks for finding and reporting this!
