### ISSUE TITLE
o5m parser issue

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#329]
Libfuzzer found a pretty obscure issue in O5mParser that would cause a non-terminating loop in decode_data().

1. Calling `ensure_bytes_available` with a huge `need_bytes` value of 0xffffffffffffff7f returns true, due to the unsigned to signed long static cast:

```c++
      bool ensure_bytes_available(std::size_t need_bytes) {
          if ((m_end - m_data) >= static_cast<int64_t>(need_bytes)) {
              return true;
          }
```

2. Adding the same huge "length" value to `m_data` causes an arithmetic overflow, effectively moving m_data backwards.

```c++
      void decode_data() {
                ...
                
            m_data += length;   // -> arithmetic overflow
               //  addition of unsigned offset to 0x6110000100f6 overflowed to 0x611000010075
               // -> m_data moves backwards
```

As a consequence, decode_data() processes the same input data over and over.

My proposal would be to change the static cast in ensure_bytes_available, maybe. (m_end >= m_data) still looks pretty weird, can m_data ever move beyond m_end?

This would return an error message "o5m format error: premature end of file" instead. 

```cpp
diff --git a/include/osmium/io/detail/o5m_input_format.hpp b/include/osmium/io/detail/o5m_input_format.hpp
index a741258e..fad5ec2d 100644
--- a/include/osmium/io/detail/o5m_input_format.hpp
+++ b/include/osmium/io/detail/o5m_input_format.hpp
@@ -166,7 +166,7 @@ namespace osmium {
                 }
 
                 bool ensure_bytes_available(std::size_t need_bytes) {
-                    if ((m_end - m_data) >= static_cast<int64_t>(need_bytes)) {
+                    if ((m_end >= m_data) && (m_end - m_data) >= static_cast<uint64_t>(need_bytes)) {
                         return true;
                     }
```

Test case:

```
echo -n "/+AEbzVjMgAAAAFTdDVjdHlwZUljRQAv4ARvMgAAAAEAL0NFAENFAP//////AQAAAAAAAAAAAAAAAAAAAP///zAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJf/+/////////wEA////////////////////////////////////////////////////////////AAX/////////////////////////////////AAU=" | base64 -d | osmium cat - -F o5m -f xml
```

**Comment by joto** [comment]
Thanks for finding this. Your solution doesn't work though: First, the `m_end >= m_data` should always be true anyway, the added check doesn't change anything here. More importantly, you change the `static_cast<int64_t>` to a `static_cast<uint64_t>` which is a noop here, because `need_bytes` is `size_t` which will be the same as `uint64_t` on a 64bit system. The reason for the cast was to avoid a comparison between signed and unsigned value.

I believe the solution is to do it the other way around and cast `m_end - m_data` which will always be positive to `size_t`.

**Comment by mmd-osm** [comment]
I agree, your approach makes much more sense, the cast to uint64_t was rather pointless. I retested my test case, and it looks good. There are still one or two unrelated locations in the o5m parser that are triggering segmentation faults. Once I have a clearer picture, I will open another issue with more details. Thanks again for the quick fix!
