### ISSUE TITLE
o5m parser issue, part 2

### ISSUE THREAD

**Issue by mmd-osm** [osmcode/libosmium#330]
Another issue triggering segfaults in the o5m parser seems to be a missing end check in decode_info: 

We need at least one more byte to determine if an info section is available, that's why I think it would be best to raise an exception here.

```c++
diff --git a/include/osmium/io/detail/o5m_input_format.hpp b/include/osmium/io/detail/o5m_input_format.hpp
index b81386ff..3443eccd 100644
--- a/include/osmium/io/detail/o5m_input_format.hpp
+++ b/include/osmium/io/detail/o5m_input_format.hpp
@@ -344,6 +344,9 @@ namespace osmium {
 
                 const char* decode_info(osmium::OSMObject& object, const char** dataptr, const char* const end) {
                     const char* user = "";
+                    if (*dataptr == end) {
+                      throw o5m_error{"premature end of file while parsing object metadata"};
+                    }
 
                     if (**dataptr == 0x00) { // no info section
                         ++*dataptr;
```

Test case:

```
echo -n "/+AEbzVtMgAAEgERAAAAAAAAAAAAAAAAAAAAAAAAAAALAA==" | base64 -d | ./osmium cat - -F o5m -f xml
```

**Comment by mmd-osm** [comment]
I'm also experiencing other crashes in the o5m parser, which I haven't analyzed yet in more detail. I'm posting them here nonetheless, and will amend them with further findings as soon as they're available. Oftentimes, the crash location is caused by some missing check in another location, like in the example above.

1. Sporadic segfault 

The following test case triggers a segfault in about 50% of runs. There might be some data race, which is randomly triggering the segfault.

```
echo -n "/+AEbzVtMgcAEBAQEBAQAAD/4ARvNW0y7AAQEBAQ9u///wAA7OwAAOzs7BHsAP8A" | base64 -d | osmium cat --no-progress - -F o5m -f xml
```

osmium cat results in either:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
</osm>
o5m format error: reference to non-existing string in table
```
or:

```
<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6" generator="osmium/1.13.1">
Segmentation fault (core dumped)
```

2. decode_tags, update_pointer

```
echo -n "/+AEbzVtMv///xEEbzVtMv///xER///+ERER/////////wAAAAD/4ADgBCU1bTL///8RBG81bTL///8REf///hEREf////////8AABDxAAA=" | base64 -d | osmium cat --no-progress - -F o5m -f xml
```

Crash location:  osmium::io::detail::O5mParser::decode_tags - `const bool update_pointer = (**dataptr == 0x00);`

3. decode_tags, while loop

```
echo -n "/+AEbzVtMgAAAAAAAAAAKCgoKAARERERERERERF2EREREREREREREQEREREREREREREREREREREREREREfUAAAAAAAAAAAAA7/4AABEREREREQAAAAAAACgoKCgAEREREf////////9+p5PqHAYAAFsAAAARERERERE0bQAAAAD/ECAABgCYAOAEbzVtAAAy" | base64 -d | osmium cat --no-progress - -F o5m -f xml
```

Crash location: osmium::io::detail::O5mParser::decode_tags - `while (*data++) {`

**Comment by joto** [comment]
I believe I fixed all the issues.

**Comment by mmd-osm** [comment]
Thanks for tracking down the remaining issues! I ran the fuzzing process again for a few hours, and luckily no further issues in the o5m parser showed up.
