### ISSUE TITLE
Anychance to have a C interface ?

### ISSUE THREAD

**Issue by gabyfle** [osmcode/libosmium#331]
What's up !

`libosmium` is actually the fastest OSM-data library I know.

I got a little issue. I would need to use `libosmium` for other languages that only have a C interface.

Does anyone knows if there is a C interface of `libosmium` that I can use ?

Thanks

**Comment by joto** [comment]
No there isn't and it isn't something that can be done easily. Libosmium uses C++ templates in many places (which is one reason why it is so fast), but that isn't something that can be used from C. Making libosmium usable from C or from other languages via a C interface would be a big undertaking and, even then, you couldn't take advantage of all the stuff that libosmium offers and the full performance, but only parts of it. So unless somebody is putting up a lot of money for this, this is unlikely to happen any time soon.
