### ISSUE TITLE
Increase maximimum integers in opl_parser_functions.hpp

### ISSUE THREAD

**Issue by tsmock** [osmcode/libosmium#336]
Stupid question: Is there any particular reason why `16` was picked here?

https://github.com/osmcode/libosmium/blob/7316c657e724cc72b71a5c6fb89da1381622eab9/include/osmium/io/detail/opl_parser_functions.hpp#L210-L213

Why not something like `(int) floor(log(std::numeric_limits<T>.max())`? (This should be 18, `log((2^64)/2 - 1) = 18.96` -> 18 for 64 bit integers). 

Ideally, this function would allow integers up to 2^63 - 1 and down to -2^63 + 1.

Alternatively, an if statement like
```cpp
                    if (value > 922337203685477580 && n > 1 && **s <='7') {
                        throw opl_error("integer too long", *s);
                    }
```
could be added in the while loop. Although that is an additional if statement (up to 18x more statements), and I don't know how badly that will tank performance.

**Comment by joto** [comment]
You are right. The `16` was probably because I was lazy and thought: I don't want to think about where the limit is exactly and nobody will use these large numbers anyway because they will, most likely, make problems somewhere else.

I have changed it to 18 digits now (19d4e5f4). Not sure I want to do the better check you propose, I'll have to think about that.

**Comment by tsmock** [comment]
Fair enough. I was going to fork it and create a merge request if you either didn't remember why or thought it was just an arbitrary decision.

As a heads up, documentation says
> The value of std::numeric_limits<T>::digits10 is the number of base-10 digits that can be represented by the type T without change, that is, any number with this many significant decimal digits can be converted to a value of type T and back to decimal form, without change due to rounding or overflow. For base-radix types, it is the value of digits (digits-1 for floating-point types) multiplied by log 10(radix) and rounded down. 

so you have changed it to `19` digits in 19d4e5f instead of `18`, unless I misunderstood something. Which is possible. But it covers the full `long` range now.

**Comment by joto** [comment]
The `::digits10` returns `18`. The `+ 1` which makes it 19 is needed because the decrement of `n` happens before the check. So I believe this doesn't lead to an overflow.

**Comment by tsmock** [comment]
OK. Fair enough.
