### ISSUE TITLE
Unable to compile with c++20  when using precompiled binaries

### ISSUE THREAD

**Issue by kelteseth** [osmcode/libosmium#339]
## What version of libosmium are you using?
- vcpkg with version 2.17

## What operating system and compiler are you using?
- Windows 10 MSVC 2019 16.10

## What did you do exactly?
- I compile my project with **c++20**. Libosmium is compiled by vcpkg with the default c++ version. But because pool.h uses **std::result_of**

https://github.com/osmcode/libosmium/blob/9543c8898bb5e60f9bf40e4fb6cd039db456e25f/include/osmium/thread/pool.hpp#L221
that was removed in **c++ 20**, I'm unable to compile my project resulting in:
```
D:\vcpkg\installed\x64-windows\include\osmium\thread\pool.hpp:215: error: C2039: 'result_of': is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\future(37): note: see declaration of 'std'
```

Other projects have the same problem and a solution: https://github.com/ReactiveX/RxCpp/issues/530#issuecomment-648896581

Change to:

``` cpp
     std::future<typename std::invoke_result <TFunction>::type> submit(TFunction&& func) {
                using result_type = typename std::invoke_result<TFunction>::type;

                std::packaged_task<result_type()> task{std::forward<TFunction>(func)};
                std::future<result_type> future_result{task.get_future()};
                m_work_queue.push(std::move(task));

                return future_result;
            }
```

`std::invoke_result` is a **c++17** feature, so this would mean to upgrade libosmium to **c++17**. Upgrading to a 4-year-old c++ version is reasonable IMHO. 

- https://en.cppreference.com/w/cpp/compiler_support#cpp17

**Comment by kelteseth** [comment]
@joto thanks!! It compiles nicely when I disable the tests, because catch uses the removed `uncaught_exception`.  If you make a patch release, I will create a pull request to update the vcpkg version. Cheers! 🎉

**Comment by joto** [comment]
Thanks for the info. There seems still to be a problem with VS though, the CI is reporting problems that need fixing.

Also: The removed `uncaught_exception` is a big problem. We are stuck on an older version of catch for unrelated reasons. And I am not going to release a new version with tests not working. This is probably going to take a while.

**Comment by kelteseth** [comment]
Ubuntu 16.04 LTS uses GCC 5.4 and is end of life since April this year. 18.04 LTS uses GCC 7.4.0 and clang 6.0  that supports all of c++17, so I think it is reasonable to switch to it, but it is your call 😊

**Comment by joto** [comment]
libosmium master should now compile in C++20 mode and all tests should work.

**Comment by kelteseth** [comment]
@joto thank you! I'm on vacation will test this in 2 weeks :)

**Comment by joto** [comment]
I haven't heard anything back so I assume this is solved. Please open a new issue if there are still problems.

**Comment by kelteseth** [comment]
@joto ah yes sorry totally forgot about this. Thanks!
