### ISSUE TITLE
Incorrect proj usage

### ISSUE THREAD

**Issue by AMDmi3** [osmcode/libosmium#345]
libosimum 2.17.2, proj 8.2.1, FreeBSD 13.1

It's impossible to use proj support in libosmium with up to date PROJ, as `proj_api.h` which osmium detects and includes was removed:

https://github.com/OSGeo/PROJ/blob/8.2.1/docs/source/news.rst#800-release-notes

**Comment by joto** [comment]
This is why the code in libosmium using the Proj API has been deprecated for a while. The manual says this:

> Only the old proj_api.h based API is supported. If you need this to work with newer versions of Proj.4, have a look at https://github.com/osmcode/osmium-proj for some untested experimental code.
