### ISSUE TITLE
io_test_bzip2 fails on Alpine Linux

### ISSUE THREAD

**Issue by brawer** [osmcode/libosmium#353]
Test `io_test_bzip2` fails when building libosmum v2.18.0 on Alpine Linux 3.16.1.

The Alpine Linux distribution is commonly used in container-based cloud environments because its container images are much smaller than those of Debian or Ubuntu. Of course nobody would want to parse OSM files on embedded systems, but Alpine-based containers are often used for cloud servers and indexing pipelines.

## How to reproduce

1. Put the following content into a file called `Dockerfile`.
2. Run `docker build -t bugreport .` on the command line. I’m using a MacBook, but any other host system with Docker support should work as well. If you don’t like Docker, [Buildah](https://buildah.io/) is a free-as-in-speech alternative, but I haven’t tried.

```Dockerfile
FROM alpine:3.16.1

RUN apk add --no-cache build-base cmake git \
  boost boost-dev \
  bzip2 bzip2-dev \
  expat expat-dev \
  lz4 lz4-dev

WORKDIR /build

RUN git clone https://github.com/mapbox/protozero --single-branch --branch v1.7.1 && cd /build/protozero && mkdir build && cd build && cmake .. && make && make test && make install && rm -rf /build/protozero

RUN git clone https://github.com/osmcode/libosmium --single-branch --branch v2.18.0 && cd /build/libosmium && mkdir build && cd build && cmake .. && make

RUN cd /build/libosmium/build && make test

CMD /bin/sh
```

## Expected

All tests should pass.

## Observed

Test case `io_test_bzip2` is failing. For more details, comment out the second-last line in the above `Dockerfile` (the one that calls `make test`), build the container again, and then log into the virtual machine with `docker run -it bugreport`. When doing this and running the failing test case manually, I’m getting the following output:

```
# cd /build/libosmium/test

/build/libosmium/test # /build/libosmium/build/test/io_test_bzip2

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
io_test_bzip2 is a Catch v2.13.8 host application.
Run with -? for options

-------------------------------------------------------------------------------
Invalid file descriptor of bzip2-compressed file
-------------------------------------------------------------------------------
/build/libosmium/test/t/io/test_bzip2.cpp:10
...............................................................................

/build/libosmium/test/t/io/test_bzip2.cpp:11: FAILED:
  REQUIRE_THROWS_AS( osmium::io::Bzip2Decompressor{-1}, std::system_error )
because no exception was thrown where one was expected:

-------------------------------------------------------------------------------
Non-open file descriptor of bzip2-compressed file
-------------------------------------------------------------------------------
/build/libosmium/test/t/io/test_bzip2.cpp:14
...............................................................................

/build/libosmium/test/t/io/test_bzip2.cpp:16: FAILED:
  REQUIRE_THROWS_AS( osmium::io::Bzip2Decompressor{12345}, std::system_error )
because no exception was thrown where one was expected:

-------------------------------------------------------------------------------
Compressor: Invalid file descriptor for bzip2-compressed file
-------------------------------------------------------------------------------
/build/libosmium/test/t/io/test_bzip2.cpp:96
...............................................................................

/build/libosmium/test/t/io/test_bzip2.cpp:97: FAILED:
  REQUIRE_THROWS_AS( osmium::io::Bzip2Compressor(-1, osmium::io::fsync::yes), std::system_error )
because no exception was thrown where one was expected:

-------------------------------------------------------------------------------
Compressor: Non-open file descriptor for bzip2-compressed file
-------------------------------------------------------------------------------
/build/libosmium/test/t/io/test_bzip2.cpp:100
...............................................................................

/build/libosmium/test/t/io/test_bzip2.cpp:102: FAILED:
  REQUIRE_THROWS_AS( osmium::io::Bzip2Compressor(12345, osmium::io::fsync::yes), std::system_error )
because no exception was thrown where one was expected:

===============================================================================
test cases: 10 |  6 passed | 4 failed
assertions: 24 | 20 passed | 4 failed
```

**Comment by joto** [comment]
Looks a bit strange. Like something related to the build system or the catch testing framework. Alpine uses musl libc and does magic things to build with extra security. Maybe something related to that. It's not likely that I'll have the time to track that down. If somebody with some experience with Alpine can have a look, please do so.

This will probably not affect usage of Osmium in normal circumstances. The only tests failing seem to be ones a) related to bzip2 and b) checking certain error conditions which are rather unlikely in normal use.

**Comment by brawer** [comment]
So I’ve been able to track this down. The root cause is musl, whose `fdopen()` implementation (other than glibc) currently doesn’t verify the passed file descriptor. I’ve reported this as a bug to musl. Meanwhile, the following patch would fix the problem — shall I send you a pull request? For better or worse, musl doesn’t have a `__MUSL__` macro; see [their FAQ](https://wiki.musl-libc.org/faq.html#Q:-Why-is-there-no-%3Ccode%3E__MUSL__%3C/code%3E-macro?).

```patch
diff --git a/include/osmium/io/bzip2_compression.hpp b/include/osmium/io/bzip2_c
ompression.hpp
index bed64375..88b63949 100644
--- a/include/osmium/io/bzip2_compression.hpp
+++ b/include/osmium/io/bzip2_compression.hpp
@@ -112,6 +112,12 @@ namespace osmium {
 #ifdef _MSC_VER
                     osmium::detail::disable_invalid_parameter_handler diph;
 #endif
+
+                    // musl fdopen() does not check fd
+                    if (fcntl(fd, F_GETFD) < 0) {
+                        throw std::system_error{errno, std::system_category(), "bad fd"};
+                    }
+
                     m_file = fdopen(fd, mode);
                     if (!m_file) {
```

**Comment by brawer** [comment]
According to [this reply on the musl mailing list](https://www.openwall.com/lists/musl/2022/08/04/2), musl will continue to return no error when `fdopen()` gets an invalid file descriptor.
