### ISSUE TITLE
AppVeyor builds fail due to missing LZ4

### ISSUE THREAD

**Issue by brawer** [osmcode/libosmium#355]
The AppVeyor configuration for libosmium appears to be broken. For example, see [this AppVeyor build for a pull request](https://ci.appveyor.com/project/lonvia/libosmium-eq41p/builds/44375100/job/wb1t5cr9xoc84tnw) that fails with the following error message. The pull request is unrelated to the error; probably the AppVeyor config needs to be updated.

```
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LZ4 (missing: LZ4_LIBRARY LZ4_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLZ4.cmake:24 (find_package_handle_standard_args)
  cmake/FindOsmium.cmake:121 (find_package)
  CMakeLists.txt:173 (find_package)
-- Configuring incomplete, errors occurred!
```

**Comment by brawer** [comment]
Nuget has an LZ4 package: https://www.nuget.org/packages/lz4/

**Comment by brawer** [comment]
@smasherprog, since you’re maintaining [a bunch of nuget packages](https://www.nuget.org/profiles/smasherprog) including [lz4](https://www.nuget.org/packages/lz4/), would you perhaps be interested to build and maintain a nuget package `lz4.v140` with pre-compiled native object files?

Context: [Osmium](https://osmcode.org/libosmium/) is a multiplatform C++ library for processing OpenStreetMap data. To make sure it doesn’t break on Windows, there’s a continuous build on AppVeyor, but it’s been broken for a while due to a newly added dependency on LZ4. I [tried fixing this](https://github.com/osmcode/libosmium/pull/356) by using @smasherprog’s [lz4 nuget package](https://www.nuget.org/packages/lz4/). However, the linker fails because it cannot open file `C:\projects\lz4.1.3.1.2\build\native\lib\x64\Debug\liblz4d.lib`; see [error log](https://ci.appveyor.com/project/lonvia/libosmium-eq41p/builds/44381814/job/4oyg4b8o2y7k3apd). Indeed, looking at the [package contents](https://nuget.info/packages/lz4/1.3.1.2), there’s no content in `build\native\lib\x64\Debug`. Could that be added? I know very little about nuget, Visual Studio, or the Windows platform in general (my last serious project had been on Windows NT 3.51, ahem), so I don’t feel confident to do this myself.

**Comment by joto** [comment]
The appveyor build isn't actually that important. It is rather an old setup and I just left it in, because I had it anyway. It would be more important to fix the Github Windows builds.

**Comment by brawer** [comment]
Oh, that’s good to know! In that case, should the AppVeyor project be shut down, and its config file deleted? Assuming there’s not much value in keeping a broken build around.

**Comment by smasherprog** [comment]
Just saw this comment. I dont maintain that library any more. I am more than happy to make you a contributor on it if you want!
