### ISSUE TITLE
installation make error

### ISSUE THREAD

**Issue by jireh-H** [osmcode/libosmium#359]
## What version of libosmium are you using?

2.18.0

## What operating system and compiler are you using?

Ubuntu 18.04 
gcc 9.5.0

## Tell us something about your system

8GB
virtual machine
8 CPUs

## What did you do exactly?

cmake ..
make

## What did you expect to happen?

successed installation

## What did happen instead?

after "cmake .." , there were raiseing "Skipped test index/test_id_to_location because a dependency was disabled/not found"

after "make" , there were some errors as follow :
[ 66%] Linking CXX executable geom_test_ogr
/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgdal.so: undefined reference to 'sqlite3_column_origin_name'

/usr/lib/gcc/x86_64-linux-gnu/7/../../../../lib/libgdal.so: undefined reference to 'sqlite3_column_table_name'
collect2: error: ld returned 1 exit status
test/CMakeFiles/geom_test_ogr.dir/build.make:96: recipe for target 'test/geom_test_ogr' failed
make[2]: *** [test/geom_test_ogr] Error 1
CMakeFiles/Makefile2:2884: recipe for target 'test/CMakeFiles/geom_test_ogr.dir/all' failed
make[1]: *** [test/CMakeFiles/geom_test_ogr.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by joto** [comment]
Looks like some library incompatibility problem. Is this a stock Ubuntu 18.04 with only Ubuntu packages installed? I suggest you try a newer Version of Ubuntu, 18.04 is quite old. Please post the whole output of `cmake`, that might tell us something.
