### ISSUE TITLE
Performance Issues with `timegm` called from `parse_timestamp` on iOS 16.2

### ISSUE THREAD

**Issue by molind** [osmcode/libosmium#363]
## What version of libosmium are you using?

I am using the master branch.

## What operating system and compiler are you using?

I am using Apple Clang version 14.0.0 (clang-1400.0.29.202) from Xcode 14.2.0.

## What did you do exactly?

I'm using libosmium to create GeoJSON from OSM data and then visualize it on a map. During performance profiling, I found that the timegm() function significantly slows down the parsing of a 100kb OSM file, taking about 3-4 seconds.

## What did you expect to happen?

I expected the process to be quick.

## What did happen instead?

Clearly, timegm is slow on both iOS and macOS.

## What did you do to try analyzing the problem?

I recorded an app profile session in Instruments. Then I replaced the call to timegm with a return 0; and checked again. After this change, it parsed the OSM file in milliseconds.

Would you consider adding a platform-independent solution from date.h or a solution from [this article](https://blog.reverberate.org/2020/05/12/optimizing-date-algorithms.html)? It provides both benchmarks and a possible solution for date parsing.

**Comment by mmd-osm** [comment]
Did you see on your traces, if timegm was called from multiple threads at the same time? I’ve seen some lock contention due to some global lock on Ubuntu as well, causing some slowdown. Maybe you’re experiencing similar issues?

**Comment by molind** [comment]
No, It's called from osmium::io::Reader::parser_thread 

```
2.32 s   97.5%	0 s	 	 osmium::io::Reader::parser_thread  0x9745c8
2.32 s   97.5%	0 s	 	  decltype(static_cast<void (*>(fp)(static_cast<std::__1::reference_wrapper<osmium::thread::Pool>>(fp0), static_cast<int>(fp0), static_cast<std::__1::reference_wrapper<std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> >>(fp0), static_cast<std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >>(fp0), static_cast<std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> > >>(fp0), static_cast<std::__1::promise<osmium::io::Header>>(fp0), static_cast<std::__1::atomic<unsigned long>*>(fp0), static_cast<osmium::osm_entity_bits::type>(fp0), static_cast<osmium::io::read_meta>(fp0), static_cast<osmium::io::buffers_type>(fp0), static_cast<bool>(fp0))) std::__1::__invoke<void (*)(osmium::thread::Pool&, int, std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> const&, osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> >&, std::__1::promise<osmium::io::Header>&&, std::__1::atomic<unsigned long>*, osmium::osm_entity_bits::type, osmium::io::read_meta, osmium::io::buffers_type, bool), std::__1::reference_wrapper<osmium::thread::Pool>, int, std::__1::reference_wrapper<std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> >, std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> > >, std::__1::promise<osmium::io::Header>, std::__1::atomic<unsigned long>*, osmium::osm_entity_bits::type, osmium::io::read_meta, osmium::io::buffers_type, bool>(void (*&&)(osmium::thread::Pool&, int, std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> const&, osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> >&, std::__1::promise<osmium::io::Header>&&, std::__1::atomic<unsigned long>*, osmium::osm_entity_bits::type, osmium::io::read_meta, osmium::io::buffers_type, bool), std::__1::reference_wrapper<osmium::thread::Pool>&&, int&&, std::__1::reference_wrapper<std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> >&&, std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >&&, std::__1::reference_wrapper<osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> > >&&, std::__1::promise<osmium::io::Header>&&, std::__1::atomic<unsigned long>*&&, osmium::osm_entity_bits::type&&, osmium::io::read_meta&&, osmium::io::buffers_type&&, bool&&)
2.32 s   97.5%	0 s	 	   osmium::io::Reader::parser_thread(osmium::thread::Pool&, int, std::__1::function<std::__1::unique_ptr<osmium::io::detail::Parser, std::__1::default_delete<osmium::io::detail::Parser> > (osmium::io::detail::parser_arguments&)> const&, osmium::thread::Queue<std::__1::future<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >&, osmium::thread::Queue<std::__1::future<osmium::memory::Buffer> >&, std::__1::promise<osmium::io::Header>&&, std::__1::atomic<unsigned long>*, osmium::osm_entity_bits::type, osmium::io::read_meta, osmium::io::buffers_type, bool)
2.32 s   97.5%	0 s	 	    osmium::io::detail::Parser::parse()
2.32 s   97.5%	0 s	 	     osmium::io::detail::XMLParser::run()
2.32 s   97.5%	25.00 ms	 	      osmium::io::detail::XMLParser::ExpatXMLParser::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool)
2.29 s   96.3%	0 s	 	       osmium::io::detail::XMLParser::ExpatXMLParser::start_element_wrapper(void*, char const*, char const**)
2.29 s   96.3%	0 s	 	        osmium::io::detail::XMLParser::ExpatXMLParser::start_element_wrapper(void*, char const*, char const**)::'lambda'(osmium::io::detail::XMLParser&)::operator()(osmium::io::detail::XMLParser&) const
2.29 s   96.0%	0 s	 	         osmium::io::detail::XMLParser::data_level_element(char const*, char const**, bool)
2.29 s   96.0%	0 s	 	          osmium::io::detail::XMLParser::init_object(osmium::OSMObject&, char const**)
2.29 s   96.0%	0 s	 	           void osmium::io::detail::XMLParser::check_attributes<osmium::io::detail::XMLParser::init_object(osmium::OSMObject&, char const**)::'lambda'(char const*, char const*)>(char const**, osmium::io::detail::XMLParser::init_object(osmium::OSMObject&, char const**)::'lambda'(char const*, char const*)&&)
2.29 s   96.0%	0 s	 	            osmium::io::detail::XMLParser::init_object(osmium::OSMObject&, char const**)::'lambda'(char const*, char const*)::operator()(char const*, char const*) const
2.29 s   96.0%	1.00 ms	 	             osmium::OSMObject::set_attribute(char const*, char const*)
2.28 s   95.9%	0 s	 	              osmium::OSMObject::set_timestamp(char const*)
2.28 s   95.8%	2.28 s	 	               osmium::detail::parse_timestamp(char const*)
```

**Comment by joto** [comment]
We have too much spezialized inline code in libosmium already because of performance or because we want to avoid dependencies on external libraries. So I am reluctant to add more.

Maybe we can find out why this is so slow. Maybe there some IO involved, like a lookup in a timezone database or something like that?

And to step back a bit: If you are performance concious, why are you using a text-based format for the data in the first place. If you use PBF format, you avoid this problem altogether.

**Comment by molind** [comment]
@joto The issue with `timegm` lies deep within the system, and unfortunately, even if we locate it, we won't be able to do much about it. Fixing `timegm` is out of the question. The only option I see is to replace the usage of `timegm` with a cross-platform implementation of our own. In our case, `tm` is always in UTC, so there's no need to use a complex function that will calculate the timestamp for us. A really good implementation was shown in this article: https://blog.reverberate.org/2020/05/12/optimizing-date-algorithms.html. 

As for the use of PBF, I would be happy to use it, but as far as I understand, the `/api/0.6/map` can't deliver data in PBF format. I would be glad to be mistaken about this.

**Comment by joto** [comment]
I suggest you take up the issue of the slow `timegm` implementation with your vendor.

Sorry, but I fail to see the necessity to improve parsing speed here when you are doing an expensive network call anyway.

**Comment by mmd-osm** [comment]
By the way, extending on the previous comment, `/api/0.6/map`  is only permitted to be used for editing apps (please c.f. https://operations.osmfoundation.org/policies/api/).

If you're planning to use this in the context of some navigation app, you need to reconsider your whole approach anyway, and this performance issue may be irrelevant after all.

**Comment by molind** [comment]
@joto no problem. I'm totally understand you way to keep up with standard system implementation. I'll fork it and speedup in that fork. Network call to download small bbox is under 1 second. Parsing could be under 10ms, but now it's 2-4 sec. Considerable overhead thrown for nothing.

@mmd-osm It's for [OpenStreetEditor](https://github.com/OpenStreetEditor/OpenStreetEditor) (temporary name). It [uses](https://github.com/OpenStreetEditor/OpenStreetEditor/blob/main/OpenStreetEditor/bridges/osmium.mm#L32) libosmium to convert osm data to geojson to display it on the map.

**Comment by mmd-osm** [comment]
@molind : thank you for providing some relevant context. I think you're well within the scope of the API usage policy, so nothing to worry about here.

I'm wondering, if you need the timestamp at all for your GeoJSON result. Of course, it would be helpful for a user to know how old an object is, but (a later) diff upload wouldn't strictly depend on this information. The object version is sufficient in that case.

**Comment by joto** [comment]
This is getting off-topic. Closing here because there is no further action in libosmium.

**Comment by mmd-osm** [comment]
Well, I thought of something like metadata_options where we could tell the XML parser to only handle a limited set of metadata fields. Maybe that's a bit too specialized, and it's not clear, if this is even an option here. Ok to close here.
