### ISSUE TITLE
Fractional seconds in XML timestamps

### ISSUE THREAD

**Issue by mibe** [osmcode/libosmium#364]
## What version of libosmium are you using?
2.19.0 (in conjunction with osmium 1.15.0)

## What operating system and compiler are you using?
Debian 12 with osmium-tool package

## Tell us something about your system
irrelevant

## What did you do exactly?
`osmium sort srtm.osm -o asdf.osm`

## What did you expect to happen?
Osmium / libosmium should successfully parse the attached file. 
[srtm.osm.zip](https://github.com/osmcode/libosmium/files/12285389/srtm.osm.zip)

## What did happen instead?
`can not parse timestamp: XXX`

## What did you do to try analyzing the problem?
In [osmium.detail.parse_timestamp()](https://github.com/osmcode/libosmium/blob/345d19054c64e864e3995a309a2e775d9551adf9/include/osmium/osm/timestamp.hpp#L82C35-L82C35) fractional seconds are not supported.

So I was wondering if the OSM XML is using [xs:dateTime](https://www.w3.org/TR/xmlschema-2/#dateTime) for the timestamps? Because the XML spec allows an (optional) fractional part of the seconds. Maybe they could be supported (and technically ignored) in libosmium too?

**Comment by joto** [comment]
Fractional seconds are not supported, because Osmium is for OSM data and OSM data doesn't have them. If you have other data that has more detailed timestamps, you have to convert that data somehow.

See also osmcode/osmium-tool#267.

**Comment by mibe** [comment]
Thanks for clarification!
