### ISSUE TITLE
Reader class cannot record file types

### ISSUE THREAD

**Issue by Duacai** [osmcode/libosmium#372]
I encountered a prompt when using OSMIUM that it does not support PBF format.
This is my code: osmium:: io:: Reader reader {"/Res/OEM/planet-230925. osm. pbf"};
I have checked the source code and found that the Reader did not register any type, which caused the wrapper std:: function to be null. I am using the latest version (2.20.0). May I know how to use it? Thank you very much.

**Comment by joto** [comment]
https://osmcode.org/libosmium/manual.html#input-and-output
