### ISSUE TITLE
windows build is failing according to https://osmcode.org/status.html

### ISSUE THREAD

**Issue by matkoniecz** [osmcode/libosmium#376]
## What operating system and compiler are you using?

Lubuntu 20.04, no compiler

## Tell us something about your system

not really relevant but I can provide info

## What did you do exactly?

opened https://osmcode.org/status.html

## What did you expect to happen?

No failing badges

## What did happen instead?

A failing badge

## What did you do to try analyzing the problem?

This badge is missing from https://github.com/osmcode/libosmium?tab=readme-ov-file#libosmium - maybe it should be added there or removed from website?

**Comment by joto** [comment]
That doesn't mean anything really. CI builds on Github work. I should probably clean up that status site at some point.

**Comment by matkoniecz** [comment]
> CI builds on Github work.

It seems that some are failing

```
Run vcpkg install geos:x64-windows gdal:x64-windows proj4:x64-windows
Computing installation plan...
error: while looking for proj4:x64-windows:
C:\vcpkg\ports\proj4: error: proj4 does not exist
```

https://github.com/osmcode/libosmium/actions/runs/9434967462/job/25988173721

**Comment by joto** [comment]
Unfortunately the Github CI is very unreliable, they always change things around, so this is not unexpected. I'll debug it at some point if and when I have the time.

**Comment by joto** [comment]
This has all been fixed.
