### ISSUE TITLE
Simplify finding Osmium with dependencies (CMake)

### ISSUE THREAD

**Issue by alex85k** [osmcode/libosmium#52]
After adding advanced FindOsmium to osmium-contrib, I noticed that it can also be included to main libosmium distribution. This will allow users to simply take FindOsmium.cmake from it sources and also make build scripts easier to maintain.

@joto Could you have a look? (and check on Linux)
https://github.com/alex85k/libosmium/commit/39f1d20be33cd9cf26f10f846afeefc269dec90a

**Comment by joto** [comment]
@alex85k: not sure this is still relevant after all the recent cmake config changes. Can we close this?

**Comment by alex85k** [comment]
@joto: Oh, I forgot about it and have too little time now... 
This can be closed, if new compilation issues will arise, I'll create new tickets.
