### ISSUE TITLE
make doc fails

### ISSUE THREAD

**Issue by tomhughes** [osmcode/libosmium#57]
Running `make doc` in a clean checkout fails with:

```
make: *** No rule to make target `doc/xml/classosmium_1_1*', needed by `doc/classes.txt'.  Stop.
```

running it a second time completes successfully.

I think the problem is that the wildcard is expanded early, when the files don't yet exist. On the second run they do exist so the wildcard can match.

**Comment by joto** [comment]
Fixed now by new cmake based build.
