### ISSUE TITLE
Appveyor config

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#60]
I have added an appveyor config, but it is only a start and it doesn't work yet. See [appveyor](https://ci.appveyor.com/project/Mapbox/libosmium). I don't understand enough about windows builds and how to use the nuget stuff so that cmake will find the libraries. The config is just bits and pieces stolen from other configs so maybe I am doing it all wrong.

@alex85k: Maybe you can take a look.

**Comment by springmeyer** [comment]
Yes, would make sense to extend the `mapnik-depedencies` scripts to help address the easy installation of pre-built dependencies for libosmium. @BergWerkGIS and I are planning is to get https://github.com/mapbox/mason going on windows soon, which is the successor to https://github.com/BergWerkGIS/mapnik-dependencies, so that would be the ideal solution when ready.

**Comment by BergWerkGIS** [comment]
@joto any idea what's wrong?


![libosmium-cmake](https://cloud.githubusercontent.com/assets/4549888/5653478/dce44f8a-96ba-11e4-842a-dd3a654262c7.png)

I did:

```
git clone https://github.com/osmcode/libosmium.git
cd libosmium
mkdir build
cd build

cmake .. ^
-DBOOST_ROOT=%PKGDIR%\boost ^
-DOSMPBF_LIBRARY=C:\mb\mapnik-dependencies-64\packages\OSM-binary\deploy\lib\osmpbf.lib ^
-DOSMPBF_INCLUDE_DIR=C:\mb\mapnik-dependencies-64\packages\OSM-binary\deploy\include ^
-DPROTOBUF_LIBRARY=%PKGDIR%\protobuf\vsprojects\%BUILDPLATFORM%\%BUILD_TYPE%\libprotobuf-lite.lib ^
-DPROTOBUF_INCLUDE_DIR=%PKGDIR%\protobuf\src ^
-DZLIB_LIBRARY=C:\mb\mapnik-dependencies-64\packages\zlib\zlib.lib ^
-DZLIB_INCLUDE_DIR=C:\mb\mapnik-dependencies-64\packages\zlib ^
-DEXPAT_LIBRARY=C:\mb\mapnik-dependencies-64\packages\expat\win32\bin\Release\libexpat.lib ^
-DEXPAT_INCLUDE_DIR=C:\mb\mapnik-dependencies-64\packages\expat\lib ^
-DBZIP2_LIBRARIES=C:\mb\mapnik-dependencies-64\packages\bzip2\libbz2.lib ^
-DBZIP2_INCLUDE_DIR=C:\mb\mapnik-dependencies-64\packages\bzip2

```

**Comment by BergWerkGIS** [comment]
@springmeyer thanks. Yes, forward slashes solve this. Already discussed with @joto on chat.

Problem is, we use backward slashes in all our env vars.

Solved it [with a string replace (`\` -> `/`) just for the bzip2.lib path](https://github.com/BergWerkGIS/mapnik-dependencies/blob/0747678afde9caf65a3c08c897493e5637c29d9d/scripts/build_libosmium.bat#L32-L35).

**Comment by BergWerkGIS** [comment]
Seems, I got all deps working.

Current problem:
Conflicts between `zlib` and `gdal`.
I think, because we build gdal with tiff, which we build with zlib.

@joto I suppose libosmium doesn't need tiff support?
Should be enough to create a gdal build without tiff?

![libosmium-zlib](https://cloud.githubusercontent.com/assets/4549888/5662508/471d3770-973a-11e4-9277-c9b97005fdde.png)

**Comment by joto** [comment]
@BergWerkGIS Osmium itself doesn't need Tiff support, but at least one of the examples (`node_density` in https://github.com/osmcode/osmium-contrib) does. So eventually it would be good to solve this, but not highest priority.

Lets get what we have into the appveyor config and see where we are then.

**Comment by springmeyer** [comment]
@BergWerkGIS - looks like gdal may be statically linking zlib? Perhaps the problem is we need to dynamically link gdal to both libtiff and zlib (and this may fix https://github.com/mapbox/mason/issues/7 at the same time?)

**Comment by BergWerkGIS** [comment]
@joto solved the `zlib` issue by linking to `gdal_i.lib` instead of `gdal.lib`.

But I have a new error (target: `geom_test_factory_with_projection`):

```
C:\mapbox\mapnik-dependencies-32\packages\libosmium\include\osmium/util/cast.hpp(58): error C2338: unnecessary static_cast_with_assert when casting into type of equal or larger size
```

![libosmium-unnecessary-static-cast](https://cloud.githubusercontent.com/assets/4549888/5684708/6e209ef8-9833-11e4-9eef-21f0320304a2.png)

**Comment by joto** [comment]
@BergWerkGIS Are you are using a 32bit system? 32bit are not fully supported, see #56.

**Comment by BergWerkGIS** [comment]
@joto you were right, 64bit did get me past that error.
Afterwards I had to move some header files around for `gdal` and `sparsehash`.
Now I'm stuck at a `zlib` error.
Might have something to do that zlib gets built as part of `libpng`.
Will investigate further and try a dedicated build of `zlib`.

**Comment by BergWerkGIS** [comment]
@joto 
A dedicated zlib build and [some other changes](https://github.com/BergWerkGIS/mapnik-dependencies/blob/47104c800968088bf85d750e5edaae5e7c6d2de5/patches/libosmium.diff) got me to __82%__.

Now I get `error C2280: attempting to reference a deleted function`.
Any ideas?

![libosmium-type-traits](https://cloud.githubusercontent.com/assets/4549888/5691404/70f90372-98c4-11e4-9214-1f7242dfa9a3.png)

**Comment by BergWerkGIS** [comment]
Full output for above mentioned error:
https://gist.github.com/BergWerkGIS/007c0bc8938f5734323b

**Comment by BergWerkGIS** [comment]
Just for the record: [commenting project `osmium_convert`](https://github.com/BergWerkGIS/mapnik-dependencies/commit/8f1a0802afdc9973203ac651f4f51287104c5eac#diff-939b90e7eadd603075510f647a1a76b0R10) made the process run through to 100%.

**Comment by BergWerkGIS** [comment]
Latest build error that stopped the process at 1% was due to using `-DCMAKE_BUILD_TYPE=Dev` with sets flag `Werror` [here](https://github.com/osmcode/libosmium/blob/711f4789f3716f62260cecddbee647c27ae13b4a/CMakeLists.txt#L231).
It seems that this is not available on Windows.

**Comment by BergWerkGIS** [comment]
@joto 
YES! :rocket: 
Finally AppVeyor is working, but the `attempting to reference a deleted function` error [still persists](https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.14#L1061).


Should I issue a [PR with the changes to appveyor.yml]
(https://github.com/BergWerkGIS/libosmium/compare/osmcode:master...master)?

**Comment by joto** [comment]
Everything compiles now on Appveyor. In addition appveyor is not set up so that `Release` and `Dev` builds are both checked. And I have added a call to `ctest`. The tests don't run all through. I will open extra issues for those cases.
