### ISSUE TITLE
Appveyor: projection test fails

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#63]
The test using the proj.4 library fails:

```
21: Projection
21: -------------------------------------------------------------------------------
21: C:\projects\libosmium\test\t\geom\test_projection.cpp(7)
21: ...............................................................................
21:
21: C:\projects\libosmium\test\t\geom\test_projection.cpp(15): FAILED:
21: due to unexpected exception with message:
21: creation of CRS failed: No such file or directory
```

My guess is that the library doesn't find the `proj` file. On Linux this usually is at `/usr/share/proj/epsg`.

**Comment by springmeyer** [comment]
Yes, probably need to set PROJ_LIB environment to point to the location of the `epsg` files inside the SDK.

**Comment by joto** [comment]
@BergWerkGIS: Can you have a look?

**Comment by BergWerkGIS** [comment]
Test passed successfully:
https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.23/job/6kb9aug66pwo81qh#L781

Adding missing `proj.dll` to binary package and setting `PROJ_LIB` env var solved it:
https://github.com/BergWerkGIS/libosmium/blob/04ef1b2b35c51735414d78351867ddf41d080e96/appveyor.yml#L31
