### ISSUE TITLE
Multiple warnings about narrowing conversions.

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#64]
MSVC spits out multiple warnings about narrowing conversions. On Linux I had all of them fixed, so we have to find out whats different on the Windows platform and fix them. See https://ci.appveyor.com/project/Mapbox/libosmium .

**Comment by BergWerkGIS** [comment]
Concerning `warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data`.

On Win 64bit `size_t` is `unsigned long`.

http://stackoverflow.com/questions/2570036/why-does-converting-from-a-size-t-to-an-unsigned-int-give-me-a-warning/2570037#2570037

**Comment by joto** [comment]
Looking at those cases it seems they should all be okay. They happen when calling library functions such as `read` and `write` and on Linux they use the right types as I found them in the documentations. Maybe those functions are defined differently on Windows? How can I find out about those function signatures on Windows?

**Comment by BergWerkGIS** [comment]
e.g., the problem [here ![image](https://cloud.githubusercontent.com/assets/4549888/5788474/cdf5bebc-9e37-11e4-9195-aab4345a8c31.png)](https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.39/job/o2obdc6hhb3nxnko#L404) is that `size_t` is `unsigned long long`

![image](https://cloud.githubusercontent.com/assets/4549888/5788443/426b96b0-9e36-11e4-9f58-559226f72a2a.png)

whereas the third parameter to `write` is just `unsigned int`
![image](https://cloud.githubusercontent.com/assets/4549888/5788444/59711736-9e36-11e4-866f-1ce471a46496.png)

The first place to look for definitions is [Microsoft Developer Network (MSDN)](http://msdn.microsoft.com/) (Although I must admit it is a nightmare to search or find anything).

e.g.:
Definition for [`_write`](http://msdn.microsoft.com/en-us/library/1570wh78.aspx) from the 
[C Run-Time Library Reference: CRT Alphabetical Function Reference](http://msdn.microsoft.com/en-us/library/634ca0c2.aspx)

Another way (if you have a Windows machine) might be to [install Visual Studio](http://www.visualstudio.com/en-us/downloads/visual-studio-2015-downloads-vs) and hover over the functions, like I did for the screenshots.
You can get Windows VMs at [modern.IE (by Microsoft)](https://www.modern.ie/en-us/virtualization-tools).

Visual Studio also features a nice "Peek Definition" feature that displays definitions inline:

![image](https://cloud.githubusercontent.com/assets/4549888/5788489/3baf5cfa-9e39-11e4-89b3-d9d588420d0a.png)

**Comment by joto** [comment]
Okay, thanks for those infos. Looks like these basic library functions have different signatures on Windows than on Linux. This could take some while to sort it all out. We have also take into account 32bit builds (see #56).

**Comment by joto** [comment]
Have all been fixed since.
