### ISSUE TITLE
Appveyor test failures

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#65]
Some of the tests just fail with `***Exception: Other` which doesn't tell us much. See for instance 
https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.34/job/6wl4j5es1upnavmm#L811 .

@BergWerkGIS: Can you try to run the tests manually and see whether you can find out whats wrong here?

**Comment by BergWerkGIS** [comment]
Found the problem, need to include `geos.dll`, `gdal111.dll` and `libexpat.dll` into the deps package.

**Comment by BergWerkGIS** [comment]
With the latest binary deps package (including missing DLLs) these errors are gone:
https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.23/job/6kb9aug66pwo81qh

It is also necessary to add them to the PATH:
https://github.com/BergWerkGIS/libosmium/blob/04ef1b2b35c51735414d78351867ddf41d080e96/appveyor.yml#L33-L42

**Comment by BergWerkGIS** [comment]
BTW: still have to work on the build of a complete `geos.dll`.

i just commented function `GEOSClipByRect_r` which prevented a successful build of `geos.dll`.
