### ISSUE TITLE
Enable multi-os on Travis

### ISSUE THREAD

**Issue by springmeyer** [osmcode/libosmium#75]
I am going to email Travis support to request multi-os support is enabled for this repo (http://docs.travis-ci.com/user/multi-os/). This will allow osx and linux to be tested each commit and will avoid the need to create a separate branch with `language: objective-c` (like I am doing now).

 - [x] Hear back from travis on enabling the repo
 - [x] Refactor the .travis.yml to be cross platform

**Comment by springmeyer** [comment]
Okay, travis support has enabled multi-os support so now we can add:

```yml
os:
  - linux
  - osx
```

And a single commit to master will build on both platforms. However the `.travis.yml` will need refactored to work on OSX, so that is the next step.

**Comment by joto** [comment]
Done in 33d479d.
