### ISSUE TITLE
Tests not run on appveyor build

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#77]
For some reason the tests are not run on the appveyor builds. They are built correctly it seems, but are later not run with messages like:

   38: Test command: NOT_AVAILABLE
   Test not available in configuration "Dev".

This looks like it is due to `cmake` being run with `-C %config&`, but without that it doesn't work either.

**Comment by joto** [comment]
Maybe some hints here: http://stackoverflow.com/questions/4065345/how-to-run-cmake-unit-tests-with-msbuild-exe

Is the hardcoded `Release` in https://github.com/osmcode/libosmium/blob/master/appveyor.yml#L70 correct? Shouldn't this be `%config%`?

@BergWerkGIS

**Comment by BergWerkGIS** [comment]
Yes, `/p:Configuration=Release` is correct.

These are the configurations of the VS solution:
![image](https://cloud.githubusercontent.com/assets/4549888/6135208/11a35286-b167-11e4-9198-464311c3aec6.png)

Still working on the tests locally.
Will trace back on the commits, they once worked.

**Comment by BergWerkGIS** [comment]
Somehow I cannot wrap my head around cmake/ctest to make the tests work when using generator `-G "Visual Studio 14 Win64"`.

A work arround that works for me locally:
* `cmake -G "Visual Studio 14 Win64"`
* `msbuild`
* `del CMakeCache.txt`
* `cmake .. -LA -G "NMake Makefiles"`
* `ctest`

AppVeyor is still running at the moment:
https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.35

**Comment by BergWerkGIS** [comment]
@joto 

Not a pretty solution, but it at least it works for now (only 1 failed test):
https://ci.appveyor.com/project/BergWerkGIS/libosmium/build/1.0.35/job/c35x2i4qf7kpo0tp#L2089

I'll keep searching for a clean solution nevertheless.

**Comment by joto** [comment]
We figured it out. CMAKE_CONFIGURATION_TYPES wasn't set right in CMake config. Now the tests run.
