### ISSUE TITLE
MSVC 2013 is or is not supported?

### ISSUE THREAD

**Issue by bdiscoe** [osmcode/libosmium#78]
Trying to build osmium with vc12 (2013) gives compile errors like:

osmium/io/compression.hpp(78): error C2146: syntax error : missing ';' before identifier 'size_t'
\osmium/util/options.hpp(73): error C2610: 'osmium::util::Options::Options(osmium::util::Options &&)' : is not a special member function which can be defaulted
osmium/util/options.hpp(105): error C3646: 'noexcept' : unknown override specifier

These appear related to support of bleeding-edge C++11 features, perhaps even beyond what vc12 supports?  The build instructions say nothing about what version of VC osmium requires.

**Comment by springmeyer** [comment]
I recommend 2014 CTP or the 2015 Preview. We did almost get things working with 2013 but it's no longer targeted. We are focusing on 2014 CTP 4 as per the appveyor build: https://github.com/osmcode/libosmium/blob/master/appveyor.yml#L19. the reason for 2014 rather than 2015 is just that we've not had time to fully test 2015.

**Comment by springmeyer** [comment]
forgot to mention. 2014 is not fully working yet either. current blocker is a fix for 2013 that breaks with 2014. tracking this at https://github.com/osmcode/libosmium/pull/74

**Comment by joto** [comment]
I have added this information to the wiki at https://github.com/osmcode/libosmium/wiki/Building-Libosmium#building-on-windows .

**Comment by joto** [comment]
@springmeyer, @BergWerkGIS: Can we check different versions of the compiler in parallel on appveyor?

**Comment by springmeyer** [comment]
@joto. not in the same appveyor file but easily in a second branch.

**Comment by BergWerkGIS** [comment]
@bdiscoe
You might be able to get it working with VS2013 and the [Visual C++ Compiler November 2013 CTP](http://www.microsoft.com/en-us/download/details.aspx?id=41151) installed, but we haven't tested this.

It should be easy to get working if you follow the instructions in [windows-build](https://github.com/mapbox/windows-builds):

Make sure you system meets the requirements: https://github.com/mapbox/windows-builds#requirements

Then execute these commands: 
https://github.com/mapbox/windows-builds#building-osmium

**Comment by BergWerkGIS** [comment]
Closing, preferred and tested compiler as of today is `VS2015 RC`.
