### ISSUE TITLE
Osmium: Disabled Google SparseHash library because we can't detect whether we are on a 64bit system.

### ISSUE THREAD

**Issue by ltog** [osmcode/libosmium#83]
First of all, thank you @joto for https://github.com/joto/osmi-addresses/commit/e07389d4d3abc5ec54881f75ba51945ecfe1149f

I tried to test it and ran into a problem while following https://github.com/osmcode/libosmium/wiki/Building-Libosmium#building-on-linux-and-mac-osx :  After the step

    cmake ..

I get the error message

    ...
    -- Check size of google::sparsetable<int>::size_type - failed
    CMake Warning at cmake/FindOsmium.cmake:244 (message):
      Osmium: Disabled Google SparseHash library because we can't detect whether
      we are on a 64bit system.
    ...

I'm on Ubuntu 14.10 64-bit and installed `libsparsehash-dev` from the Ubuntu repository. The version of `cmake` (also from the Ubuntu repository) is 2.8.12.2.

What do you recommend?

**Comment by DerDakon** [comment]
I suspect this happens because the "LANGUAGE CXX" passed to check_type_size() is only supported since CMake 3.0. Can you please try out if #110 fixes your issue?
