### ISSUE TITLE
Need I to copy include files manually to use them in my software?

### ISSUE THREAD

**Issue by ltog** [osmcode/libosmium#84]
Do I need to copy the files in https://github.com/osmcode/libosmium/tree/master/include/osmium manually to e.g. `/usr/include` or is there an automatic mechanism (e.g. Makefile) to do so? Is this documented somewhere?

**Comment by joto** [comment]
Libosmium works like any other C/C++ library in that regard. You can use it uninstalled or install it (in this case `make install` should work and by default install in `/usr/local/include`). The key is telling the build system of your application where to find it. If it is installed in `/usr/include` or `/usr/local/include` your build system will probably just find it. If it is installed somewhere else or not installed at all, you can set the `CPATH` environment variable, it should be a list of `:`-separated directories where the compiler searches for include files.
Also please have a look at https://github.com/osmcode/libosmium/wiki/Using-Libosmium-in-your-own-projects . If you are using CMake this page explains how to include libosmium.

**Comment by ltog** [comment]
Thanks, I missed the `make install` part.

I noticed that the `install` make target is only available after `cmake .. ; ccmake ..` (described in https://github.com/osmcode/libosmium/wiki/Building-Libosmium)

**Comment by joto** [comment]
The whole `Makefile` is only available after the CMake step. Thats how it is supposed to work.
