### ISSUE TITLE
SQLite driver not available on Appveyor build

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#85]
The `testdata-overview` test on the `Dev` build in Appveyor failes with `SQLite driver not available.` I guess that means GDAL/OGR was compiled without SQLite support.

**Comment by BergWerkGIS** [comment]
@joto could you provide an AppVeyor link to the error?
I've looked thru the builds till 1 month ago and couldn't find it.
Maybe I missed it?

**Comment by joto** [comment]
https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.102/job/per6bwf83axbx06h#L5239

**Comment by BergWerkGIS** [comment]
Dependency package updated.
Build running ATM:
https://ci.appveyor.com/project/Mapbox/libosmium/build/1.0.104

**Comment by joto** [comment]
Now fails with
```ERROR 6: OGR was built without libspatialite support
... sorry, creating/writing any SpatiaLite DB is unsupported
```

**Comment by BergWerkGIS** [comment]
That's correct `SpatiaLite` is not yet activated.
Are there any other drivers that are needed?

**Comment by joto** [comment]
Currently I think not, but Shapefiles could be useful in the future I guess.

**Comment by BergWerkGIS** [comment]
Shapefiles are already enabled.

**Comment by joto** [comment]
Has been fixed in the meantime.
