### ISSUE TITLE
Support for compression 'bzip2' not compiled into this binary.

### ISSUE THREAD

**Issue by abdultz** [osmcode/libosmium#90]
After issuing `make` as per the Readme the compilation is successful
The binaries are of the examples are also generated successfully
I am not able to use the osmium_serdump utility
See the following:

`user@ubu1410:~/Desktop/libosmium-master/build/examples$ ./osmium_serdump /home/user/Downloads/2012/planet-120912.osm.bz2 /home/user/Downloads/2012/ser/
terminate called after throwing an instance of 'std::runtime_error'
  what():  Support for compression 'bzip2' not compiled into this binary.
Aborted (core dumped)`

I even included the following in CMakeLists.txt file for the examples
list(APPEND EXAMPLE_LIBS_${example} ${BZIP2_LIBRARIES})

`ldd` doesnt shows the `bzip.so` as one of the dependencies

**Comment by joto** [comment]
If you don't have the necessary libraries at compile time, support for bzip2 will not be included.

Do you have the development files for bzip2 installed? (On Debian/Ubuntu you need the `libbz2-dev` package.) Does CMake warn you when it is run ("Osmium: Can not find some libraries for XML input/output, please install them or configure the paths.")?

If this doesn't help, go to your `build` directory and call `ccmake .` and type `t`. Check the `BZIP2_*` settings.

**Comment by abdultz** [comment]
Yes, I do have it (libbz2-dev) installed
output:
`BZIP2_FOUND`
I even included `#include <bzlib.h>` and the program compiles without any warnings
