### ISSUE TITLE
cmake produces: 'google::sparsetable<int>::size_type - failed'

### ISSUE THREAD

**Issue by ghost** [osmcode/libosmium#91]
Since commit 95cf62 cmake cant build google::sparsetable anymore. 
It crashes with the following error:
```
-- Check size of google::sparsetable<int>::size_type
-- Check size of google::sparsetable<int>::size_type - failed
```
I reproduced this error on Ubuntu 14.04.2 LTS (64-bit) with:
* gcc-4.8 and gcc-4.9.
* cmake version 2.8.12.2

this issue may also be related to https://github.com/osmcode/libosmium/issues/83

**Comment by joto** [comment]
Ubuntu 14.04 is, by now, a rather old system. Maybe the sparsetable implementation is different. I can't reproduce this on newer systems. @ghost is this still a problem for you?
